services:
    user-db:
        image: postgres:18.3-alpine
        restart: always
        env_file:
            - ../../services/auth-service/.env
        volumes:
            - user_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1",
                ]
            interval: 5s
            timeout: 2s
            retries: 10

    world-db:
        image: postgis/postgis:18-3.6-alpine
        platform: linux/amd64
        restart: always
        env_file:
            - ../../services/world-service/.env
        volumes:
            - world_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1",
                ]
            interval: 5s
            timeout: 2s
            retries: 10

    # kafka:
    #     image: confluentinc/cp-kafka:latest
    #     container_name: kafka
    #     ports:
    #         - "9092:9092"
    #     environment:
    #         # KRaft mode configuration
    #         KAFKA_NODE_ID: ${KAFKA_NODE_ID}
    #         KAFKA_PROCESS_ROLES: "broker,controller"
    #         KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
    #         KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

    #         # Listeners setup
    #         KAFKA_LISTENERS: ${KAFKA_LISTENERS}
    #         KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
    #         KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

    #         # Default topics / settings
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #         KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    #         # Topics created at start
    #         KAFKA_CREATE_TOPICS: ${KAFKA_CREATE_TOPICS}
    #     healthcheck:
    #         test:
    #             [
    #                 "CMD",
    #                 "kafka-topics",
    #                 "--bootstrap-server",
    #                 "kafka:29092",
    #                 "--list",
    #             ]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 10

    world-service:
        build:
            context: ../../../
            dockerfile: backend/services/world-service/Dockerfile
        restart: on-failure
        env_file:
            - ../../services/world-service/.env
        depends_on:
            world-db:
                condition: service_healthy

    auth-service:
        build:
            context: ../../../
            dockerfile: backend/services/auth-service/Dockerfile
        restart: on-failure
        env_file:
            - ../../services/auth-service/.env
        depends_on:
            user-db:
                condition: service_healthy

    api-gateway:
        build:
            context: ../../../
            dockerfile: backend/services/api-gateway/Dockerfile
        restart: on-failure
        env_file:
            - ../../services/api-gateway/.env
        depends_on:
            - auth-service
            - world-service
        ports:
            - "8080:8080"

volumes:
    user_postgres_data:
    world_postgres_data:

networks:
    default:
        name: airlinesim_net
