// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: operations.proto

package operationspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationsService_CreateCountry_FullMethodName    = "/auth.v1.OperationsService/CreateCountry"
	OperationsService_ChangeCountry_FullMethodName    = "/auth.v1.OperationsService/ChangeCountry"
	OperationsService_ListCountries_FullMethodName    = "/auth.v1.OperationsService/ListCountries"
	OperationsService_DeleteCountry_FullMethodName    = "/auth.v1.OperationsService/DeleteCountry"
	OperationsService_CreateRegion_FullMethodName     = "/auth.v1.OperationsService/CreateRegion"
	OperationsService_ChangeRegion_FullMethodName     = "/auth.v1.OperationsService/ChangeRegion"
	OperationsService_ListRegions_FullMethodName      = "/auth.v1.OperationsService/ListRegions"
	OperationsService_DeleteRegion_FullMethodName     = "/auth.v1.OperationsService/DeleteRegion"
	OperationsService_CreateRegionLink_FullMethodName = "/auth.v1.OperationsService/CreateRegionLink"
	OperationsService_ChangeRegionLink_FullMethodName = "/auth.v1.OperationsService/ChangeRegionLink"
	OperationsService_ListRegionLinks_FullMethodName  = "/auth.v1.OperationsService/ListRegionLinks"
	OperationsService_DeleteRegionLink_FullMethodName = "/auth.v1.OperationsService/DeleteRegionLink"
	OperationsService_CreateAirport_FullMethodName    = "/auth.v1.OperationsService/CreateAirport"
	OperationsService_ChangeAirport_FullMethodName    = "/auth.v1.OperationsService/ChangeAirport"
	OperationsService_ListAirports_FullMethodName     = "/auth.v1.OperationsService/ListAirports"
	OperationsService_DeleteAirport_FullMethodName    = "/auth.v1.OperationsService/DeleteAirport"
)

// OperationsServiceClient is the client API for OperationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// operations service
type OperationsServiceClient interface {
	// create country, returns id of newly created country
	CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// change country
	ChangeCountry(ctx context.Context, in *ChangeCountryRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// list countries
	ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error)
	// delete country
	DeleteCountry(ctx context.Context, in *DeleteCountryRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// create region, returns id of newly created region
	CreateRegion(ctx context.Context, in *CreateRegionRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// change region
	ChangeRegion(ctx context.Context, in *ChangeRegionRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// list regions
	ListRegions(ctx context.Context, in *ListRegionsRequest, opts ...grpc.CallOption) (*ListRegionsResponse, error)
	// delete region
	DeleteRegion(ctx context.Context, in *DeleteRegionRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// create region link, returns id of newly created region link
	CreateRegionLink(ctx context.Context, in *CreateRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// change region link
	ChangeRegionLink(ctx context.Context, in *ChangeRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// list region links
	ListRegionLinks(ctx context.Context, in *ListRegionLinksRequest, opts ...grpc.CallOption) (*ListRegionLinksResponse, error)
	// delete region link
	DeleteRegionLink(ctx context.Context, in *DeleteRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// create airport, returns id of newly created airport
	CreateAirport(ctx context.Context, in *CreateAirportRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// change airport
	ChangeAirport(ctx context.Context, in *ChangeAirportRequest, opts ...grpc.CallOption) (*IDResponse, error)
	// list airports
	ListAirports(ctx context.Context, in *ListAirportsRequest, opts ...grpc.CallOption) (*ListAirportsResponse, error)
	// delete airport
	DeleteAirport(ctx context.Context, in *DeleteAirportRequest, opts ...grpc.CallOption) (*IDResponse, error)
}

type operationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsServiceClient(cc grpc.ClientConnInterface) OperationsServiceClient {
	return &operationsServiceClient{cc}
}

func (c *operationsServiceClient) CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_CreateCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ChangeCountry(ctx context.Context, in *ChangeCountryRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_ChangeCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCountriesResponse)
	err := c.cc.Invoke(ctx, OperationsService_ListCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) DeleteCountry(ctx context.Context, in *DeleteCountryRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_DeleteCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) CreateRegion(ctx context.Context, in *CreateRegionRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_CreateRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ChangeRegion(ctx context.Context, in *ChangeRegionRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_ChangeRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ListRegions(ctx context.Context, in *ListRegionsRequest, opts ...grpc.CallOption) (*ListRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegionsResponse)
	err := c.cc.Invoke(ctx, OperationsService_ListRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) DeleteRegion(ctx context.Context, in *DeleteRegionRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_DeleteRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) CreateRegionLink(ctx context.Context, in *CreateRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_CreateRegionLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ChangeRegionLink(ctx context.Context, in *ChangeRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_ChangeRegionLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ListRegionLinks(ctx context.Context, in *ListRegionLinksRequest, opts ...grpc.CallOption) (*ListRegionLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegionLinksResponse)
	err := c.cc.Invoke(ctx, OperationsService_ListRegionLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) DeleteRegionLink(ctx context.Context, in *DeleteRegionLinkRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_DeleteRegionLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) CreateAirport(ctx context.Context, in *CreateAirportRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_CreateAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ChangeAirport(ctx context.Context, in *ChangeAirportRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_ChangeAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ListAirports(ctx context.Context, in *ListAirportsRequest, opts ...grpc.CallOption) (*ListAirportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAirportsResponse)
	err := c.cc.Invoke(ctx, OperationsService_ListAirports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) DeleteAirport(ctx context.Context, in *DeleteAirportRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, OperationsService_DeleteAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsServiceServer is the server API for OperationsService service.
// All implementations must embed UnimplementedOperationsServiceServer
// for forward compatibility.
//
// operations service
type OperationsServiceServer interface {
	// create country, returns id of newly created country
	CreateCountry(context.Context, *CreateCountryRequest) (*IDResponse, error)
	// change country
	ChangeCountry(context.Context, *ChangeCountryRequest) (*IDResponse, error)
	// list countries
	ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error)
	// delete country
	DeleteCountry(context.Context, *DeleteCountryRequest) (*IDResponse, error)
	// create region, returns id of newly created region
	CreateRegion(context.Context, *CreateRegionRequest) (*IDResponse, error)
	// change region
	ChangeRegion(context.Context, *ChangeRegionRequest) (*IDResponse, error)
	// list regions
	ListRegions(context.Context, *ListRegionsRequest) (*ListRegionsResponse, error)
	// delete region
	DeleteRegion(context.Context, *DeleteRegionRequest) (*IDResponse, error)
	// create region link, returns id of newly created region link
	CreateRegionLink(context.Context, *CreateRegionLinkRequest) (*IDResponse, error)
	// change region link
	ChangeRegionLink(context.Context, *ChangeRegionLinkRequest) (*IDResponse, error)
	// list region links
	ListRegionLinks(context.Context, *ListRegionLinksRequest) (*ListRegionLinksResponse, error)
	// delete region link
	DeleteRegionLink(context.Context, *DeleteRegionLinkRequest) (*IDResponse, error)
	// create airport, returns id of newly created airport
	CreateAirport(context.Context, *CreateAirportRequest) (*IDResponse, error)
	// change airport
	ChangeAirport(context.Context, *ChangeAirportRequest) (*IDResponse, error)
	// list airports
	ListAirports(context.Context, *ListAirportsRequest) (*ListAirportsResponse, error)
	// delete airport
	DeleteAirport(context.Context, *DeleteAirportRequest) (*IDResponse, error)
	mustEmbedUnimplementedOperationsServiceServer()
}

// UnimplementedOperationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsServiceServer struct{}

func (UnimplementedOperationsServiceServer) CreateCountry(context.Context, *CreateCountryRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCountry not implemented")
}
func (UnimplementedOperationsServiceServer) ChangeCountry(context.Context, *ChangeCountryRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeCountry not implemented")
}
func (UnimplementedOperationsServiceServer) ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCountries not implemented")
}
func (UnimplementedOperationsServiceServer) DeleteCountry(context.Context, *DeleteCountryRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCountry not implemented")
}
func (UnimplementedOperationsServiceServer) CreateRegion(context.Context, *CreateRegionRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRegion not implemented")
}
func (UnimplementedOperationsServiceServer) ChangeRegion(context.Context, *ChangeRegionRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeRegion not implemented")
}
func (UnimplementedOperationsServiceServer) ListRegions(context.Context, *ListRegionsRequest) (*ListRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegions not implemented")
}
func (UnimplementedOperationsServiceServer) DeleteRegion(context.Context, *DeleteRegionRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRegion not implemented")
}
func (UnimplementedOperationsServiceServer) CreateRegionLink(context.Context, *CreateRegionLinkRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRegionLink not implemented")
}
func (UnimplementedOperationsServiceServer) ChangeRegionLink(context.Context, *ChangeRegionLinkRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeRegionLink not implemented")
}
func (UnimplementedOperationsServiceServer) ListRegionLinks(context.Context, *ListRegionLinksRequest) (*ListRegionLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegionLinks not implemented")
}
func (UnimplementedOperationsServiceServer) DeleteRegionLink(context.Context, *DeleteRegionLinkRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRegionLink not implemented")
}
func (UnimplementedOperationsServiceServer) CreateAirport(context.Context, *CreateAirportRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAirport not implemented")
}
func (UnimplementedOperationsServiceServer) ChangeAirport(context.Context, *ChangeAirportRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeAirport not implemented")
}
func (UnimplementedOperationsServiceServer) ListAirports(context.Context, *ListAirportsRequest) (*ListAirportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAirports not implemented")
}
func (UnimplementedOperationsServiceServer) DeleteAirport(context.Context, *DeleteAirportRequest) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAirport not implemented")
}
func (UnimplementedOperationsServiceServer) mustEmbedUnimplementedOperationsServiceServer() {}
func (UnimplementedOperationsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOperationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsServiceServer will
// result in compilation errors.
type UnsafeOperationsServiceServer interface {
	mustEmbedUnimplementedOperationsServiceServer()
}

func RegisterOperationsServiceServer(s grpc.ServiceRegistrar, srv OperationsServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationsService_ServiceDesc, srv)
}

func _OperationsService_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_CreateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).CreateCountry(ctx, req.(*CreateCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ChangeCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ChangeCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ChangeCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ChangeCountry(ctx, req.(*ChangeCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ListCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ListCountries(ctx, req.(*ListCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_DeleteCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).DeleteCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_DeleteCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).DeleteCountry(ctx, req.(*DeleteCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_CreateRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).CreateRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_CreateRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).CreateRegion(ctx, req.(*CreateRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ChangeRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ChangeRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ChangeRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ChangeRegion(ctx, req.(*ChangeRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ListRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ListRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ListRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ListRegions(ctx, req.(*ListRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_DeleteRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).DeleteRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_DeleteRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).DeleteRegion(ctx, req.(*DeleteRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_CreateRegionLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegionLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).CreateRegionLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_CreateRegionLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).CreateRegionLink(ctx, req.(*CreateRegionLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ChangeRegionLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRegionLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ChangeRegionLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ChangeRegionLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ChangeRegionLink(ctx, req.(*ChangeRegionLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ListRegionLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegionLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ListRegionLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ListRegionLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ListRegionLinks(ctx, req.(*ListRegionLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_DeleteRegionLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRegionLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).DeleteRegionLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_DeleteRegionLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).DeleteRegionLink(ctx, req.(*DeleteRegionLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_CreateAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).CreateAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_CreateAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).CreateAirport(ctx, req.(*CreateAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ChangeAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ChangeAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ChangeAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ChangeAirport(ctx, req.(*ChangeAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ListAirports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAirportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ListAirports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ListAirports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ListAirports(ctx, req.(*ListAirportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_DeleteAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).DeleteAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_DeleteAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).DeleteAirport(ctx, req.(*DeleteAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationsService_ServiceDesc is the grpc.ServiceDesc for OperationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.OperationsService",
	HandlerType: (*OperationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCountry",
			Handler:    _OperationsService_CreateCountry_Handler,
		},
		{
			MethodName: "ChangeCountry",
			Handler:    _OperationsService_ChangeCountry_Handler,
		},
		{
			MethodName: "ListCountries",
			Handler:    _OperationsService_ListCountries_Handler,
		},
		{
			MethodName: "DeleteCountry",
			Handler:    _OperationsService_DeleteCountry_Handler,
		},
		{
			MethodName: "CreateRegion",
			Handler:    _OperationsService_CreateRegion_Handler,
		},
		{
			MethodName: "ChangeRegion",
			Handler:    _OperationsService_ChangeRegion_Handler,
		},
		{
			MethodName: "ListRegions",
			Handler:    _OperationsService_ListRegions_Handler,
		},
		{
			MethodName: "DeleteRegion",
			Handler:    _OperationsService_DeleteRegion_Handler,
		},
		{
			MethodName: "CreateRegionLink",
			Handler:    _OperationsService_CreateRegionLink_Handler,
		},
		{
			MethodName: "ChangeRegionLink",
			Handler:    _OperationsService_ChangeRegionLink_Handler,
		},
		{
			MethodName: "ListRegionLinks",
			Handler:    _OperationsService_ListRegionLinks_Handler,
		},
		{
			MethodName: "DeleteRegionLink",
			Handler:    _OperationsService_DeleteRegionLink_Handler,
		},
		{
			MethodName: "CreateAirport",
			Handler:    _OperationsService_CreateAirport_Handler,
		},
		{
			MethodName: "ChangeAirport",
			Handler:    _OperationsService_ChangeAirport_Handler,
		},
		{
			MethodName: "ListAirports",
			Handler:    _OperationsService_ListAirports_Handler,
		},
		{
			MethodName: "DeleteAirport",
			Handler:    _OperationsService_DeleteAirport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operations.proto",
}
