import { parse } from "yaml";

type JsonSchema = {
  $ref?: string;
  additionalProperties?: boolean | JsonSchema;
  allOf?: JsonSchema[];
  enum?: Array<number | string>;
  format?: string;
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  type?: string;
};

type SwaggerDocument = {
  definitions?: Record<string, JsonSchema>;
  paths?: Record<string, Record<string, SwaggerOperation>>;
};

type SwaggerParameter = {
  enum?: Array<number | string>;
  in?: string;
  name?: string;
  required?: boolean;
  type?: string;
};

type SwaggerOperation = {
  operationId?: string;
  parameters?: SwaggerParameter[];
  summary?: string;
  tags?: string[];
};

const bffDocsJsonPath = new URL("../../../docs/bff-openapi.json", import.meta.url);
const docsJsonPath = new URL("../../../docs/swagger.json", import.meta.url);
const docsYamlPath = new URL("../../../docs/swagger.yaml", import.meta.url);
const outputPath = new URL("../src/generated/openapi.ts", import.meta.url);

function buildObjectType(schema: JsonSchema): string {
  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties ?? {}).map(([property, propertySchema]) => {
    const optional = required.has(property) ? "" : "?";

    return `  ${JSON.stringify(property)}${optional}: ${schemaToType(propertySchema)};`;
  });

  if (entries.length === 0) {
    return "Record<string, unknown>";
  }

  return `{\n${entries.join("\n")}\n}`;
}

function collectOperations(paths: SwaggerDocument["paths"]): string {
  const operations = Object.entries(paths ?? {}).flatMap(([path, methods]) =>
    Object.entries(methods).map(([method, operation]) => ({
      method: method.toUpperCase(),
      operationId: operation.operationId ?? `${method}_${path.replaceAll(/[^a-zA-Z0-9]/g, "_")}`,
      path,
      summary: operation.summary ?? "",
      tags: operation.tags ?? [],
    })),
  );

  return JSON.stringify(operations, null, 2);
}

function collectQueryTypeBlocks(paths: SwaggerDocument["paths"]): string {
  return Object.entries(paths ?? {})
    .flatMap(([path, methods]) =>
      Object.entries(methods).map(([method, operation]) => {
        const queryParameters = operation.parameters?.filter((parameter) => parameter.in === "query") ?? [];

        if (queryParameters.length === 0) {
          return "";
        }

        const operationId = operation.operationId ?? `${method}_${path.replaceAll(/[^a-zA-Z0-9]/g, "_")}`;
        const properties = queryParameters
          .filter((parameter): parameter is SwaggerParameter & { name: string } => Boolean(parameter.name))
          .map((parameter) => {
            const optional = parameter.required ? "" : "?";

            return `  ${JSON.stringify(parameter.name)}${optional}: ${parameterToType(parameter)};`;
          });

        return `export type ${normalizeTypeName(`${operationId}Query`)} = {\n${properties.join("\n")}\n};`;
      }),
    )
    .filter(Boolean)
    .join("\n\n");
}

async function fileExists(path: URL): Promise<boolean> {
  return Bun.file(path).exists();
}

async function generate(): Promise<void> {
  const swagger = await loadSwagger();
  const definitions = swagger.definitions ?? {};
  const typeBlocks = Object.entries(definitions)
    .map(([name, schema]) => `export type ${normalizeTypeName(name)} = ${schemaToType(schema)};`)
    .join("\n\n");
  const queryTypeBlocks = collectQueryTypeBlocks(swagger.paths);

  const content = `/* eslint-disable */\n// Generated by packages/api-contracts/scripts/generate-openapi.ts.\n// Source: frontend/docs/bff-openapi.json when present; fallback is frontend/docs/swagger.json or frontend/docs/swagger.yaml.\n\n${[typeBlocks, queryTypeBlocks].filter(Boolean).join("\n\n")}\n\nexport const openApiOperations = ${collectOperations(swagger.paths)} as const;\n`;

  await Bun.write(outputPath, content);
}

function getObjectType(schema: JsonSchema): string {
  if (schema.properties) {
    return buildObjectType(schema);
  }

  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    return `Record<string, ${schemaToType(schema.additionalProperties)}>`;
  }

  return "Record<string, unknown>";
}

async function loadSwagger(): Promise<SwaggerDocument> {
  if (await fileExists(bffDocsJsonPath)) {
    return (await Bun.file(bffDocsJsonPath).json()) as SwaggerDocument;
  }

  if (await fileExists(docsYamlPath)) {
    return parse(await Bun.file(docsYamlPath).text()) as SwaggerDocument;
  }

  if (await fileExists(docsJsonPath)) {
    return (await Bun.file(docsJsonPath).json()) as SwaggerDocument;
  }

  throw new Error("No swagger.json or swagger.yaml found in frontend/docs.");
}

function parameterToType(parameter: SwaggerParameter): string {
  if (parameter.enum?.length) {
    return parameter.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  return schemaToPrimitiveType({ type: parameter.type });
}

function normalizeTypeName(name: string): string {
  const normalized = name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");

  return normalized || "UnknownSchema";
}

function refToType(ref: string): string {
  return normalizeTypeName(ref.replace("#/definitions/", ""));
}

function schemaToPrimitiveType(schema: JsonSchema): string {
  switch (schema.type) {
    case "boolean":
      return "boolean";
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    default:
      return "unknown";
  }
}

function schemaToType(schema: JsonSchema | undefined): string {
  if (!schema) {
    return "unknown";
  }

  if (schema.$ref) {
    return refToType(schema.$ref);
  }

  if (schema.allOf?.length) {
    return schema.allOf.map(schemaToType).join(" & ");
  }

  if (schema.enum?.length) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (schema.type === "array") {
    return `Array<${schemaToType(schema.items)}>`;
  }

  if (schema.type === "object" || schema.properties) {
    return getObjectType(schema);
  }

  return schemaToPrimitiveType(schema);
}

await generate();
