// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: world.proto

package worldpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateCountryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCountryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCountryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCountryRequestMultiError, or nil if none found.
func (m *CreateCountryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCountryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Iso

	// no validation rules for LocalName

	// no validation rules for IntlName

	// no validation rules for FlythroughPermissionPrice

	// no validation rules for LandPermissionPrice

	// no validation rules for CorpTaxRate

	// no validation rules for VatRate

	// no validation rules for AircraftTailCode

	// no validation rules for WikipediaLink

	if len(errors) > 0 {
		return CreateCountryRequestMultiError(errors)
	}

	return nil
}

// CreateCountryRequestMultiError is an error wrapping multiple validation
// errors returned by CreateCountryRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateCountryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCountryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCountryRequestMultiError) AllErrors() []error { return m }

// CreateCountryRequestValidationError is the validation error returned by
// CreateCountryRequest.Validate if the designated constraints aren't met.
type CreateCountryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCountryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCountryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCountryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCountryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCountryRequestValidationError) ErrorName() string {
	return "CreateCountryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCountryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCountryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCountryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCountryRequestValidationError{}

// Validate checks the field values on CreateRegionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRegionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRegionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRegionRequestMultiError, or nil if none found.
func (m *CreateRegionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRegionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for LocalCode

	// no validation rules for LocalName

	// no validation rules for IntlName

	// no validation rules for CountryId

	// no validation rules for Population

	// no validation rules for GdpPerCapita

	// no validation rules for TourismScore

	// no validation rules for BusinessScore

	// no validation rules for WikipediaLink

	if len(errors) > 0 {
		return CreateRegionRequestMultiError(errors)
	}

	return nil
}

// CreateRegionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRegionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRegionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRegionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRegionRequestMultiError) AllErrors() []error { return m }

// CreateRegionRequestValidationError is the validation error returned by
// CreateRegionRequest.Validate if the designated constraints aren't met.
type CreateRegionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRegionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRegionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRegionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRegionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRegionRequestValidationError) ErrorName() string {
	return "CreateRegionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRegionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRegionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRegionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRegionRequestValidationError{}

// Validate checks the field values on CreateRegionLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRegionLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRegionLinkRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRegionLinkRequestMultiError, or nil if none found.
func (m *CreateRegionLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRegionLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for RegionA

	// no validation rules for RegionB

	// no validation rules for Diaspora

	// no validation rules for Business

	// no validation rules for Tourism

	if len(errors) > 0 {
		return CreateRegionLinkRequestMultiError(errors)
	}

	return nil
}

// CreateRegionLinkRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRegionLinkRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRegionLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRegionLinkRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRegionLinkRequestMultiError) AllErrors() []error { return m }

// CreateRegionLinkRequestValidationError is the validation error returned by
// CreateRegionLinkRequest.Validate if the designated constraints aren't met.
type CreateRegionLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRegionLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRegionLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRegionLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRegionLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRegionLinkRequestValidationError) ErrorName() string {
	return "CreateRegionLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRegionLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRegionLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRegionLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRegionLinkRequestValidationError{}

// Validate checks the field values on CreateAirportRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAirportRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAirportRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAirportRequestMultiError, or nil if none found.
func (m *CreateAirportRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAirportRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for IcaoCode

	// no validation rules for IataCode

	// no validation rules for LocalName

	// no validation rules for IntlName

	// no validation rules for Timezone

	// no validation rules for CountryId

	// no validation rules for RegionId

	// no validation rules for Municipality

	// no validation rules for Continent

	// no validation rules for ElevationFt

	// no validation rules for MaxRunwayLengthM

	// no validation rules for WorksAtNight

	// no validation rules for MaxRunwayUsesPerDay

	// no validation rules for TurnaroundPointPrice

	// no validation rules for MaintenancePointPrice

	// no validation rules for RunwayFee

	// no validation rules for GateFee

	// no validation rules for StandFee

	// no validation rules for FuelPriceMultiplier

	// no validation rules for HomeLink

	// no validation rules for WikipediaLink

	// no validation rules for Geog

	// no validation rules for Geom

	if len(errors) > 0 {
		return CreateAirportRequestMultiError(errors)
	}

	return nil
}

// CreateAirportRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAirportRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAirportRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAirportRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAirportRequestMultiError) AllErrors() []error { return m }

// CreateAirportRequestValidationError is the validation error returned by
// CreateAirportRequest.Validate if the designated constraints aren't met.
type CreateAirportRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAirportRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAirportRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAirportRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAirportRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAirportRequestValidationError) ErrorName() string {
	return "CreateAirportRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAirportRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAirportRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAirportRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAirportRequestValidationError{}

// Validate checks the field values on IDResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IDResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IDResponseMultiError, or
// nil if none found.
func (m *IDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return IDResponseMultiError(errors)
	}

	return nil
}

// IDResponseMultiError is an error wrapping multiple validation errors
// returned by IDResponse.ValidateAll() if the designated constraints aren't met.
type IDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IDResponseMultiError) AllErrors() []error { return m }

// IDResponseValidationError is the validation error returned by
// IDResponse.Validate if the designated constraints aren't met.
type IDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IDResponseValidationError) ErrorName() string { return "IDResponseValidationError" }

// Error satisfies the builtin error interface
func (e IDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IDResponseValidationError{}
