// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: fleet.proto

package fleetpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_CreateAircraft_FullMethodName    = "/fleet.v1.FleetService/CreateAircraft"
	FleetService_ListAircraftTypes_FullMethodName = "/fleet.v1.FleetService/ListAircraftTypes"
	FleetService_GetAircraftType_FullMethodName   = "/fleet.v1.FleetService/GetAircraftType"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// fleet service
type FleetServiceClient interface {
	// create aircraft from selected aircraft type
	CreateAircraft(ctx context.Context, in *CreateAircraftRequest, opts ...grpc.CallOption) (*CreateAircraftResponse, error)
	// list available aircraft types
	ListAircraftTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAircraftTypesResponse, error)
	// get aircraft type by id
	GetAircraftType(ctx context.Context, in *GetAircraftTypeRequest, opts ...grpc.CallOption) (*AircraftType, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) CreateAircraft(ctx context.Context, in *CreateAircraftRequest, opts ...grpc.CallOption) (*CreateAircraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAircraftResponse)
	err := c.cc.Invoke(ctx, FleetService_CreateAircraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListAircraftTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAircraftTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAircraftTypesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAircraftTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetAircraftType(ctx context.Context, in *GetAircraftTypeRequest, opts ...grpc.CallOption) (*AircraftType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AircraftType)
	err := c.cc.Invoke(ctx, FleetService_GetAircraftType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
//
// fleet service
type FleetServiceServer interface {
	// create aircraft from selected aircraft type
	CreateAircraft(context.Context, *CreateAircraftRequest) (*CreateAircraftResponse, error)
	// list available aircraft types
	ListAircraftTypes(context.Context, *emptypb.Empty) (*ListAircraftTypesResponse, error)
	// get aircraft type by id
	GetAircraftType(context.Context, *GetAircraftTypeRequest) (*AircraftType, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) CreateAircraft(context.Context, *CreateAircraftRequest) (*CreateAircraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAircraft not implemented")
}
func (UnimplementedFleetServiceServer) ListAircraftTypes(context.Context, *emptypb.Empty) (*ListAircraftTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAircraftTypes not implemented")
}
func (UnimplementedFleetServiceServer) GetAircraftType(context.Context, *GetAircraftTypeRequest) (*AircraftType, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAircraftType not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_CreateAircraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAircraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateAircraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateAircraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateAircraft(ctx, req.(*CreateAircraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListAircraftTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAircraftTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAircraftTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAircraftTypes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetAircraftType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAircraftTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetAircraftType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetAircraftType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetAircraftType(ctx, req.(*GetAircraftTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAircraft",
			Handler:    _FleetService_CreateAircraft_Handler,
		},
		{
			MethodName: "ListAircraftTypes",
			Handler:    _FleetService_ListAircraftTypes_Handler,
		},
		{
			MethodName: "GetAircraftType",
			Handler:    _FleetService_GetAircraftType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleet.proto",
}
