// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fleet.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAircraftRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AircraftTypeId string                 `protobuf:"bytes,1,opt,name=aircraft_type_id,json=aircraftTypeId,proto3" json:"aircraft_type_id,omitempty"`
	BaseAirportId  string                 `protobuf:"bytes,2,opt,name=base_airport_id,json=baseAirportId,proto3" json:"base_airport_id,omitempty"`
	TailNumber     string                 `protobuf:"bytes,3,opt,name=tail_number,json=tailNumber,proto3" json:"tail_number,omitempty"`
	CurrentOwnerId string                 `protobuf:"bytes,4,opt,name=current_owner_id,json=currentOwnerId,proto3" json:"current_owner_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAircraftRequest) Reset() {
	*x = CreateAircraftRequest{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAircraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAircraftRequest) ProtoMessage() {}

func (x *CreateAircraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAircraftRequest.ProtoReflect.Descriptor instead.
func (*CreateAircraftRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAircraftRequest) GetAircraftTypeId() string {
	if x != nil {
		return x.AircraftTypeId
	}
	return ""
}

func (x *CreateAircraftRequest) GetBaseAirportId() string {
	if x != nil {
		return x.BaseAirportId
	}
	return ""
}

func (x *CreateAircraftRequest) GetTailNumber() string {
	if x != nil {
		return x.TailNumber
	}
	return ""
}

func (x *CreateAircraftRequest) GetCurrentOwnerId() string {
	if x != nil {
		return x.CurrentOwnerId
	}
	return ""
}

type CreateAircraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAircraftResponse) Reset() {
	*x = CreateAircraftResponse{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAircraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAircraftResponse) ProtoMessage() {}

func (x *CreateAircraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAircraftResponse.ProtoReflect.Descriptor instead.
func (*CreateAircraftResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAircraftResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAircraftTypeRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ManufacturerId          string                 `protobuf:"bytes,1,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	ModelName               string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	IcaoCode                string                 `protobuf:"bytes,3,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode                string                 `protobuf:"bytes,4,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	ImageUploadId           string                 `protobuf:"bytes,5,opt,name=image_upload_id,json=imageUploadId,proto3" json:"image_upload_id,omitempty"`
	MaxRangeKm              float64                `protobuf:"fixed64,6,opt,name=max_range_km,json=maxRangeKm,proto3" json:"max_range_km,omitempty"`
	CruisingSpeedKph        float64                `protobuf:"fixed64,7,opt,name=cruising_speed_kph,json=cruisingSpeedKph,proto3" json:"cruising_speed_kph,omitempty"`
	MaxPlannedSeatCapacity  float64                `protobuf:"fixed64,8,opt,name=max_planned_seat_capacity,json=maxPlannedSeatCapacity,proto3" json:"max_planned_seat_capacity,omitempty"`
	MinRunwayLengthM        float64                `protobuf:"fixed64,9,opt,name=min_runway_length_m,json=minRunwayLengthM,proto3" json:"min_runway_length_m,omitempty"`
	ProductionPointsPrice   float64                `protobuf:"fixed64,10,opt,name=production_points_price,json=productionPointsPrice,proto3" json:"production_points_price,omitempty"`
	BaseTurnaroundPoints    float64                `protobuf:"fixed64,11,opt,name=base_turnaround_points,json=baseTurnaroundPoints,proto3" json:"base_turnaround_points,omitempty"`
	BaseMaintenancePoints   float64                `protobuf:"fixed64,12,opt,name=base_maintenance_points,json=baseMaintenancePoints,proto3" json:"base_maintenance_points,omitempty"`
	MaintCostPerTakeoff     float64                `protobuf:"fixed64,13,opt,name=maint_cost_per_takeoff,json=maintCostPerTakeoff,proto3" json:"maint_cost_per_takeoff,omitempty"`
	MaintCostPerLanding     float64                `protobuf:"fixed64,14,opt,name=maint_cost_per_landing,json=maintCostPerLanding,proto3" json:"maint_cost_per_landing,omitempty"`
	MaintCostPerFlightHour  float64                `protobuf:"fixed64,15,opt,name=maint_cost_per_flight_hour,json=maintCostPerFlightHour,proto3" json:"maint_cost_per_flight_hour,omitempty"`
	DCheckIntervalFh        float64                `protobuf:"fixed64,16,opt,name=d_check_interval_fh,json=dCheckIntervalFh,proto3" json:"d_check_interval_fh,omitempty"`
	DCheckIntervalYears     float64                `protobuf:"fixed64,17,opt,name=d_check_interval_years,json=dCheckIntervalYears,proto3" json:"d_check_interval_years,omitempty"`
	DCheckOverdueMultiplier float64                `protobuf:"fixed64,18,opt,name=d_check_overdue_multiplier,json=dCheckOverdueMultiplier,proto3" json:"d_check_overdue_multiplier,omitempty"`
	FuelConsumptionPerHour  float64                `protobuf:"fixed64,19,opt,name=fuel_consumption_per_hour,json=fuelConsumptionPerHour,proto3" json:"fuel_consumption_per_hour,omitempty"`
	MtowKg                  float64                `protobuf:"fixed64,20,opt,name=mtow_kg,json=mtowKg,proto3" json:"mtow_kg,omitempty"`
	PricePerUnit            float64                `protobuf:"fixed64,21,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Characteristics         string                 `protobuf:"bytes,22,opt,name=characteristics,proto3" json:"characteristics,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateAircraftTypeRequest) Reset() {
	*x = CreateAircraftTypeRequest{}
	mi := &file_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAircraftTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAircraftTypeRequest) ProtoMessage() {}

func (x *CreateAircraftTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAircraftTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateAircraftTypeRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAircraftTypeRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *CreateAircraftTypeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CreateAircraftTypeRequest) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *CreateAircraftTypeRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *CreateAircraftTypeRequest) GetImageUploadId() string {
	if x != nil {
		return x.ImageUploadId
	}
	return ""
}

func (x *CreateAircraftTypeRequest) GetMaxRangeKm() float64 {
	if x != nil {
		return x.MaxRangeKm
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetCruisingSpeedKph() float64 {
	if x != nil {
		return x.CruisingSpeedKph
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMaxPlannedSeatCapacity() float64 {
	if x != nil {
		return x.MaxPlannedSeatCapacity
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMinRunwayLengthM() float64 {
	if x != nil {
		return x.MinRunwayLengthM
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetProductionPointsPrice() float64 {
	if x != nil {
		return x.ProductionPointsPrice
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetBaseTurnaroundPoints() float64 {
	if x != nil {
		return x.BaseTurnaroundPoints
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetBaseMaintenancePoints() float64 {
	if x != nil {
		return x.BaseMaintenancePoints
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMaintCostPerTakeoff() float64 {
	if x != nil {
		return x.MaintCostPerTakeoff
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMaintCostPerLanding() float64 {
	if x != nil {
		return x.MaintCostPerLanding
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMaintCostPerFlightHour() float64 {
	if x != nil {
		return x.MaintCostPerFlightHour
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetDCheckIntervalFh() float64 {
	if x != nil {
		return x.DCheckIntervalFh
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetDCheckIntervalYears() float64 {
	if x != nil {
		return x.DCheckIntervalYears
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetDCheckOverdueMultiplier() float64 {
	if x != nil {
		return x.DCheckOverdueMultiplier
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetFuelConsumptionPerHour() float64 {
	if x != nil {
		return x.FuelConsumptionPerHour
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetMtowKg() float64 {
	if x != nil {
		return x.MtowKg
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *CreateAircraftTypeRequest) GetCharacteristics() string {
	if x != nil {
		return x.Characteristics
	}
	return ""
}

type AircraftType struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManufacturerId          string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	ModelName               string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	IcaoCode                string                 `protobuf:"bytes,4,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode                string                 `protobuf:"bytes,5,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	ImageUploadId           string                 `protobuf:"bytes,6,opt,name=image_upload_id,json=imageUploadId,proto3" json:"image_upload_id,omitempty"`
	MaxRangeKm              float64                `protobuf:"fixed64,7,opt,name=max_range_km,json=maxRangeKm,proto3" json:"max_range_km,omitempty"`
	CruisingSpeedKph        float64                `protobuf:"fixed64,8,opt,name=cruising_speed_kph,json=cruisingSpeedKph,proto3" json:"cruising_speed_kph,omitempty"`
	MaxPlannedSeatCapacity  float64                `protobuf:"fixed64,9,opt,name=max_planned_seat_capacity,json=maxPlannedSeatCapacity,proto3" json:"max_planned_seat_capacity,omitempty"`
	MinRunwayLengthM        float64                `protobuf:"fixed64,10,opt,name=min_runway_length_m,json=minRunwayLengthM,proto3" json:"min_runway_length_m,omitempty"`
	ProductionPointsPrice   float64                `protobuf:"fixed64,11,opt,name=production_points_price,json=productionPointsPrice,proto3" json:"production_points_price,omitempty"`
	BaseTurnaroundPoints    float64                `protobuf:"fixed64,12,opt,name=base_turnaround_points,json=baseTurnaroundPoints,proto3" json:"base_turnaround_points,omitempty"`
	BaseMaintenancePoints   float64                `protobuf:"fixed64,13,opt,name=base_maintenance_points,json=baseMaintenancePoints,proto3" json:"base_maintenance_points,omitempty"`
	MaintCostPerTakeoff     float64                `protobuf:"fixed64,14,opt,name=maint_cost_per_takeoff,json=maintCostPerTakeoff,proto3" json:"maint_cost_per_takeoff,omitempty"`
	MaintCostPerLanding     float64                `protobuf:"fixed64,15,opt,name=maint_cost_per_landing,json=maintCostPerLanding,proto3" json:"maint_cost_per_landing,omitempty"`
	MaintCostPerFlightHour  float64                `protobuf:"fixed64,16,opt,name=maint_cost_per_flight_hour,json=maintCostPerFlightHour,proto3" json:"maint_cost_per_flight_hour,omitempty"`
	DCheckIntervalFh        float64                `protobuf:"fixed64,17,opt,name=d_check_interval_fh,json=dCheckIntervalFh,proto3" json:"d_check_interval_fh,omitempty"`
	DCheckIntervalYears     float64                `protobuf:"fixed64,18,opt,name=d_check_interval_years,json=dCheckIntervalYears,proto3" json:"d_check_interval_years,omitempty"`
	DCheckOverdueMultiplier float64                `protobuf:"fixed64,19,opt,name=d_check_overdue_multiplier,json=dCheckOverdueMultiplier,proto3" json:"d_check_overdue_multiplier,omitempty"`
	FuelConsumptionPerHour  float64                `protobuf:"fixed64,20,opt,name=fuel_consumption_per_hour,json=fuelConsumptionPerHour,proto3" json:"fuel_consumption_per_hour,omitempty"`
	MtowKg                  float64                `protobuf:"fixed64,21,opt,name=mtow_kg,json=mtowKg,proto3" json:"mtow_kg,omitempty"`
	PricePerUnit            float64                `protobuf:"fixed64,22,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Characteristics         string                 `protobuf:"bytes,23,opt,name=characteristics,proto3" json:"characteristics,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AircraftType) Reset() {
	*x = AircraftType{}
	mi := &file_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftType) ProtoMessage() {}

func (x *AircraftType) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftType.ProtoReflect.Descriptor instead.
func (*AircraftType) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *AircraftType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AircraftType) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *AircraftType) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AircraftType) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *AircraftType) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *AircraftType) GetImageUploadId() string {
	if x != nil {
		return x.ImageUploadId
	}
	return ""
}

func (x *AircraftType) GetMaxRangeKm() float64 {
	if x != nil {
		return x.MaxRangeKm
	}
	return 0
}

func (x *AircraftType) GetCruisingSpeedKph() float64 {
	if x != nil {
		return x.CruisingSpeedKph
	}
	return 0
}

func (x *AircraftType) GetMaxPlannedSeatCapacity() float64 {
	if x != nil {
		return x.MaxPlannedSeatCapacity
	}
	return 0
}

func (x *AircraftType) GetMinRunwayLengthM() float64 {
	if x != nil {
		return x.MinRunwayLengthM
	}
	return 0
}

func (x *AircraftType) GetProductionPointsPrice() float64 {
	if x != nil {
		return x.ProductionPointsPrice
	}
	return 0
}

func (x *AircraftType) GetBaseTurnaroundPoints() float64 {
	if x != nil {
		return x.BaseTurnaroundPoints
	}
	return 0
}

func (x *AircraftType) GetBaseMaintenancePoints() float64 {
	if x != nil {
		return x.BaseMaintenancePoints
	}
	return 0
}

func (x *AircraftType) GetMaintCostPerTakeoff() float64 {
	if x != nil {
		return x.MaintCostPerTakeoff
	}
	return 0
}

func (x *AircraftType) GetMaintCostPerLanding() float64 {
	if x != nil {
		return x.MaintCostPerLanding
	}
	return 0
}

func (x *AircraftType) GetMaintCostPerFlightHour() float64 {
	if x != nil {
		return x.MaintCostPerFlightHour
	}
	return 0
}

func (x *AircraftType) GetDCheckIntervalFh() float64 {
	if x != nil {
		return x.DCheckIntervalFh
	}
	return 0
}

func (x *AircraftType) GetDCheckIntervalYears() float64 {
	if x != nil {
		return x.DCheckIntervalYears
	}
	return 0
}

func (x *AircraftType) GetDCheckOverdueMultiplier() float64 {
	if x != nil {
		return x.DCheckOverdueMultiplier
	}
	return 0
}

func (x *AircraftType) GetFuelConsumptionPerHour() float64 {
	if x != nil {
		return x.FuelConsumptionPerHour
	}
	return 0
}

func (x *AircraftType) GetMtowKg() float64 {
	if x != nil {
		return x.MtowKg
	}
	return 0
}

func (x *AircraftType) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *AircraftType) GetCharacteristics() string {
	if x != nil {
		return x.Characteristics
	}
	return ""
}

type ListAircraftTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AircraftType        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAircraftTypesResponse) Reset() {
	*x = ListAircraftTypesResponse{}
	mi := &file_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAircraftTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAircraftTypesResponse) ProtoMessage() {}

func (x *ListAircraftTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAircraftTypesResponse.ProtoReflect.Descriptor instead.
func (*ListAircraftTypesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *ListAircraftTypesResponse) GetItems() []*AircraftType {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAircraftTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAircraftTypeRequest) Reset() {
	*x = GetAircraftTypeRequest{}
	mi := &file_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftTypeRequest) ProtoMessage() {}

func (x *GetAircraftTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftTypeRequest.ProtoReflect.Descriptor instead.
func (*GetAircraftTypeRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *GetAircraftTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Aircraft struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId                     string                 `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	CurrentOwnerId             string                 `protobuf:"bytes,3,opt,name=current_owner_id,json=currentOwnerId,proto3" json:"current_owner_id,omitempty"`
	BaseAirportId              string                 `protobuf:"bytes,4,opt,name=base_airport_id,json=baseAirportId,proto3" json:"base_airport_id,omitempty"`
	TailNumber                 string                 `protobuf:"bytes,5,opt,name=tail_number,json=tailNumber,proto3" json:"tail_number,omitempty"`
	InService                  bool                   `protobuf:"varint,6,opt,name=in_service,json=inService,proto3" json:"in_service,omitempty"`
	Status                     string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CurrentMaintenancePoints   float64                `protobuf:"fixed64,8,opt,name=current_maintenance_points,json=currentMaintenancePoints,proto3" json:"current_maintenance_points,omitempty"`
	MaxMaintenancePointsCached float64                `protobuf:"fixed64,9,opt,name=max_maintenance_points_cached,json=maxMaintenancePointsCached,proto3" json:"max_maintenance_points_cached,omitempty"`
	TotalFlightHours           float64                `protobuf:"fixed64,10,opt,name=total_flight_hours,json=totalFlightHours,proto3" json:"total_flight_hours,omitempty"`
	FhSinceLastDCheck          float64                `protobuf:"fixed64,11,opt,name=fh_since_last_d_check,json=fhSinceLastDCheck,proto3" json:"fh_since_last_d_check,omitempty"`
	TotalCycles                float64                `protobuf:"fixed64,12,opt,name=total_cycles,json=totalCycles,proto3" json:"total_cycles,omitempty"`
	ManufacturedAt             string                 `protobuf:"bytes,13,opt,name=manufactured_at,json=manufacturedAt,proto3" json:"manufactured_at,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Aircraft) Reset() {
	*x = Aircraft{}
	mi := &file_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aircraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aircraft) ProtoMessage() {}

func (x *Aircraft) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aircraft.ProtoReflect.Descriptor instead.
func (*Aircraft) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *Aircraft) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Aircraft) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Aircraft) GetCurrentOwnerId() string {
	if x != nil {
		return x.CurrentOwnerId
	}
	return ""
}

func (x *Aircraft) GetBaseAirportId() string {
	if x != nil {
		return x.BaseAirportId
	}
	return ""
}

func (x *Aircraft) GetTailNumber() string {
	if x != nil {
		return x.TailNumber
	}
	return ""
}

func (x *Aircraft) GetInService() bool {
	if x != nil {
		return x.InService
	}
	return false
}

func (x *Aircraft) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Aircraft) GetCurrentMaintenancePoints() float64 {
	if x != nil {
		return x.CurrentMaintenancePoints
	}
	return 0
}

func (x *Aircraft) GetMaxMaintenancePointsCached() float64 {
	if x != nil {
		return x.MaxMaintenancePointsCached
	}
	return 0
}

func (x *Aircraft) GetTotalFlightHours() float64 {
	if x != nil {
		return x.TotalFlightHours
	}
	return 0
}

func (x *Aircraft) GetFhSinceLastDCheck() float64 {
	if x != nil {
		return x.FhSinceLastDCheck
	}
	return 0
}

func (x *Aircraft) GetTotalCycles() float64 {
	if x != nil {
		return x.TotalCycles
	}
	return 0
}

func (x *Aircraft) GetManufacturedAt() string {
	if x != nil {
		return x.ManufacturedAt
	}
	return ""
}

type ListAircraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAircraftsRequest) Reset() {
	*x = ListAircraftsRequest{}
	mi := &file_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAircraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAircraftsRequest) ProtoMessage() {}

func (x *ListAircraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAircraftsRequest.ProtoReflect.Descriptor instead.
func (*ListAircraftsRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *ListAircraftsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListAircraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Aircraft            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAircraftsResponse) Reset() {
	*x = ListAircraftsResponse{}
	mi := &file_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAircraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAircraftsResponse) ProtoMessage() {}

func (x *ListAircraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAircraftsResponse.ProtoReflect.Descriptor instead.
func (*ListAircraftsResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *ListAircraftsResponse) GetItems() []*Aircraft {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\bfleet.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb4\x01\n" +
	"\x15CreateAircraftRequest\x12(\n" +
	"\x10aircraft_type_id\x18\x01 \x01(\tR\x0eaircraftTypeId\x12&\n" +
	"\x0fbase_airport_id\x18\x02 \x01(\tR\rbaseAirportId\x12\x1f\n" +
	"\vtail_number\x18\x03 \x01(\tR\n" +
	"tailNumber\x12(\n" +
	"\x10current_owner_id\x18\x04 \x01(\tR\x0ecurrentOwnerId\"(\n" +
	"\x16CreateAircraftResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\b\n" +
	"\x19CreateAircraftTypeRequest\x12'\n" +
	"\x0fmanufacturer_id\x18\x01 \x01(\tR\x0emanufacturerId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1b\n" +
	"\ticao_code\x18\x03 \x01(\tR\bicaoCode\x12\x1b\n" +
	"\tiata_code\x18\x04 \x01(\tR\biataCode\x12&\n" +
	"\x0fimage_upload_id\x18\x05 \x01(\tR\rimageUploadId\x12 \n" +
	"\fmax_range_km\x18\x06 \x01(\x01R\n" +
	"maxRangeKm\x12,\n" +
	"\x12cruising_speed_kph\x18\a \x01(\x01R\x10cruisingSpeedKph\x129\n" +
	"\x19max_planned_seat_capacity\x18\b \x01(\x01R\x16maxPlannedSeatCapacity\x12-\n" +
	"\x13min_runway_length_m\x18\t \x01(\x01R\x10minRunwayLengthM\x126\n" +
	"\x17production_points_price\x18\n" +
	" \x01(\x01R\x15productionPointsPrice\x124\n" +
	"\x16base_turnaround_points\x18\v \x01(\x01R\x14baseTurnaroundPoints\x126\n" +
	"\x17base_maintenance_points\x18\f \x01(\x01R\x15baseMaintenancePoints\x123\n" +
	"\x16maint_cost_per_takeoff\x18\r \x01(\x01R\x13maintCostPerTakeoff\x123\n" +
	"\x16maint_cost_per_landing\x18\x0e \x01(\x01R\x13maintCostPerLanding\x12:\n" +
	"\x1amaint_cost_per_flight_hour\x18\x0f \x01(\x01R\x16maintCostPerFlightHour\x12-\n" +
	"\x13d_check_interval_fh\x18\x10 \x01(\x01R\x10dCheckIntervalFh\x123\n" +
	"\x16d_check_interval_years\x18\x11 \x01(\x01R\x13dCheckIntervalYears\x12;\n" +
	"\x1ad_check_overdue_multiplier\x18\x12 \x01(\x01R\x17dCheckOverdueMultiplier\x129\n" +
	"\x19fuel_consumption_per_hour\x18\x13 \x01(\x01R\x16fuelConsumptionPerHour\x12\x17\n" +
	"\amtow_kg\x18\x14 \x01(\x01R\x06mtowKg\x12$\n" +
	"\x0eprice_per_unit\x18\x15 \x01(\x01R\fpricePerUnit\x12(\n" +
	"\x0fcharacteristics\x18\x16 \x01(\tR\x0fcharacteristics\"\x93\b\n" +
	"\fAircraftType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1b\n" +
	"\ticao_code\x18\x04 \x01(\tR\bicaoCode\x12\x1b\n" +
	"\tiata_code\x18\x05 \x01(\tR\biataCode\x12&\n" +
	"\x0fimage_upload_id\x18\x06 \x01(\tR\rimageUploadId\x12 \n" +
	"\fmax_range_km\x18\a \x01(\x01R\n" +
	"maxRangeKm\x12,\n" +
	"\x12cruising_speed_kph\x18\b \x01(\x01R\x10cruisingSpeedKph\x129\n" +
	"\x19max_planned_seat_capacity\x18\t \x01(\x01R\x16maxPlannedSeatCapacity\x12-\n" +
	"\x13min_runway_length_m\x18\n" +
	" \x01(\x01R\x10minRunwayLengthM\x126\n" +
	"\x17production_points_price\x18\v \x01(\x01R\x15productionPointsPrice\x124\n" +
	"\x16base_turnaround_points\x18\f \x01(\x01R\x14baseTurnaroundPoints\x126\n" +
	"\x17base_maintenance_points\x18\r \x01(\x01R\x15baseMaintenancePoints\x123\n" +
	"\x16maint_cost_per_takeoff\x18\x0e \x01(\x01R\x13maintCostPerTakeoff\x123\n" +
	"\x16maint_cost_per_landing\x18\x0f \x01(\x01R\x13maintCostPerLanding\x12:\n" +
	"\x1amaint_cost_per_flight_hour\x18\x10 \x01(\x01R\x16maintCostPerFlightHour\x12-\n" +
	"\x13d_check_interval_fh\x18\x11 \x01(\x01R\x10dCheckIntervalFh\x123\n" +
	"\x16d_check_interval_years\x18\x12 \x01(\x01R\x13dCheckIntervalYears\x12;\n" +
	"\x1ad_check_overdue_multiplier\x18\x13 \x01(\x01R\x17dCheckOverdueMultiplier\x129\n" +
	"\x19fuel_consumption_per_hour\x18\x14 \x01(\x01R\x16fuelConsumptionPerHour\x12\x17\n" +
	"\amtow_kg\x18\x15 \x01(\x01R\x06mtowKg\x12$\n" +
	"\x0eprice_per_unit\x18\x16 \x01(\x01R\fpricePerUnit\x12(\n" +
	"\x0fcharacteristics\x18\x17 \x01(\tR\x0fcharacteristics\"I\n" +
	"\x19ListAircraftTypesResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.fleet.v1.AircraftTypeR\x05items\"(\n" +
	"\x16GetAircraftTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8a\x04\n" +
	"\bAircraft\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12(\n" +
	"\x10current_owner_id\x18\x03 \x01(\tR\x0ecurrentOwnerId\x12&\n" +
	"\x0fbase_airport_id\x18\x04 \x01(\tR\rbaseAirportId\x12\x1f\n" +
	"\vtail_number\x18\x05 \x01(\tR\n" +
	"tailNumber\x12\x1d\n" +
	"\n" +
	"in_service\x18\x06 \x01(\bR\tinService\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12<\n" +
	"\x1acurrent_maintenance_points\x18\b \x01(\x01R\x18currentMaintenancePoints\x12A\n" +
	"\x1dmax_maintenance_points_cached\x18\t \x01(\x01R\x1amaxMaintenancePointsCached\x12,\n" +
	"\x12total_flight_hours\x18\n" +
	" \x01(\x01R\x10totalFlightHours\x120\n" +
	"\x15fh_since_last_d_check\x18\v \x01(\x01R\x11fhSinceLastDCheck\x12!\n" +
	"\ftotal_cycles\x18\f \x01(\x01R\vtotalCycles\x12'\n" +
	"\x0fmanufactured_at\x18\r \x01(\tR\x0emanufacturedAt\"1\n" +
	"\x14ListAircraftsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"A\n" +
	"\x15ListAircraftsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.fleet.v1.AircraftR\x05items2\xa7\x03\n" +
	"\fFleetService\x12S\n" +
	"\x0eCreateAircraft\x12\x1f.fleet.v1.CreateAircraftRequest\x1a .fleet.v1.CreateAircraftResponse\x12Q\n" +
	"\x12CreateAircraftType\x12#.fleet.v1.CreateAircraftTypeRequest\x1a\x16.fleet.v1.AircraftType\x12P\n" +
	"\x11ListAircraftTypes\x12\x16.google.protobuf.Empty\x1a#.fleet.v1.ListAircraftTypesResponse\x12K\n" +
	"\x0fGetAircraftType\x12 .fleet.v1.GetAircraftTypeRequest\x1a\x16.fleet.v1.AircraftType\x12P\n" +
	"\rListAircrafts\x12\x1e.fleet.v1.ListAircraftsRequest\x1a\x1f.fleet.v1.ListAircraftsResponseBWZUgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/fleet/v1;fleetpbb\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fleet_proto_goTypes = []any{
	(*CreateAircraftRequest)(nil),     // 0: fleet.v1.CreateAircraftRequest
	(*CreateAircraftResponse)(nil),    // 1: fleet.v1.CreateAircraftResponse
	(*CreateAircraftTypeRequest)(nil), // 2: fleet.v1.CreateAircraftTypeRequest
	(*AircraftType)(nil),              // 3: fleet.v1.AircraftType
	(*ListAircraftTypesResponse)(nil), // 4: fleet.v1.ListAircraftTypesResponse
	(*GetAircraftTypeRequest)(nil),    // 5: fleet.v1.GetAircraftTypeRequest
	(*Aircraft)(nil),                  // 6: fleet.v1.Aircraft
	(*ListAircraftsRequest)(nil),      // 7: fleet.v1.ListAircraftsRequest
	(*ListAircraftsResponse)(nil),     // 8: fleet.v1.ListAircraftsResponse
	(*emptypb.Empty)(nil),             // 9: google.protobuf.Empty
}
var file_fleet_proto_depIdxs = []int32{
	3, // 0: fleet.v1.ListAircraftTypesResponse.items:type_name -> fleet.v1.AircraftType
	6, // 1: fleet.v1.ListAircraftsResponse.items:type_name -> fleet.v1.Aircraft
	0, // 2: fleet.v1.FleetService.CreateAircraft:input_type -> fleet.v1.CreateAircraftRequest
	2, // 3: fleet.v1.FleetService.CreateAircraftType:input_type -> fleet.v1.CreateAircraftTypeRequest
	9, // 4: fleet.v1.FleetService.ListAircraftTypes:input_type -> google.protobuf.Empty
	5, // 5: fleet.v1.FleetService.GetAircraftType:input_type -> fleet.v1.GetAircraftTypeRequest
	7, // 6: fleet.v1.FleetService.ListAircrafts:input_type -> fleet.v1.ListAircraftsRequest
	1, // 7: fleet.v1.FleetService.CreateAircraft:output_type -> fleet.v1.CreateAircraftResponse
	3, // 8: fleet.v1.FleetService.CreateAircraftType:output_type -> fleet.v1.AircraftType
	4, // 9: fleet.v1.FleetService.ListAircraftTypes:output_type -> fleet.v1.ListAircraftTypesResponse
	3, // 10: fleet.v1.FleetService.GetAircraftType:output_type -> fleet.v1.AircraftType
	8, // 11: fleet.v1.FleetService.ListAircrafts:output_type -> fleet.v1.ListAircraftsResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
