// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fleet.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAircraftRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AircraftTypeId string                 `protobuf:"bytes,1,opt,name=aircraft_type_id,json=aircraftTypeId,proto3" json:"aircraft_type_id,omitempty"`
	BaseAirportId  string                 `protobuf:"bytes,2,opt,name=base_airport_id,json=baseAirportId,proto3" json:"base_airport_id,omitempty"`
	TailNumber     string                 `protobuf:"bytes,3,opt,name=tail_number,json=tailNumber,proto3" json:"tail_number,omitempty"`
	CurrentOwnerId string                 `protobuf:"bytes,4,opt,name=current_owner_id,json=currentOwnerId,proto3" json:"current_owner_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAircraftRequest) Reset() {
	*x = CreateAircraftRequest{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAircraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAircraftRequest) ProtoMessage() {}

func (x *CreateAircraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAircraftRequest.ProtoReflect.Descriptor instead.
func (*CreateAircraftRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAircraftRequest) GetAircraftTypeId() string {
	if x != nil {
		return x.AircraftTypeId
	}
	return ""
}

func (x *CreateAircraftRequest) GetBaseAirportId() string {
	if x != nil {
		return x.BaseAirportId
	}
	return ""
}

func (x *CreateAircraftRequest) GetTailNumber() string {
	if x != nil {
		return x.TailNumber
	}
	return ""
}

func (x *CreateAircraftRequest) GetCurrentOwnerId() string {
	if x != nil {
		return x.CurrentOwnerId
	}
	return ""
}

type CreateAircraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAircraftResponse) Reset() {
	*x = CreateAircraftResponse{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAircraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAircraftResponse) ProtoMessage() {}

func (x *CreateAircraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAircraftResponse.ProtoReflect.Descriptor instead.
func (*CreateAircraftResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAircraftResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\bfleet.v1\"\xb4\x01\n" +
	"\x15CreateAircraftRequest\x12(\n" +
	"\x10aircraft_type_id\x18\x01 \x01(\tR\x0eaircraftTypeId\x12&\n" +
	"\x0fbase_airport_id\x18\x02 \x01(\tR\rbaseAirportId\x12\x1f\n" +
	"\vtail_number\x18\x03 \x01(\tR\n" +
	"tailNumber\x12(\n" +
	"\x10current_owner_id\x18\x04 \x01(\tR\x0ecurrentOwnerId\"(\n" +
	"\x16CreateAircraftResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2c\n" +
	"\fFleetService\x12S\n" +
	"\x0eCreateAircraft\x12\x1f.fleet.v1.CreateAircraftRequest\x1a .fleet.v1.CreateAircraftResponseBWZUgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/fleet/v1;fleetpbb\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fleet_proto_goTypes = []any{
	(*CreateAircraftRequest)(nil),  // 0: fleet.v1.CreateAircraftRequest
	(*CreateAircraftResponse)(nil), // 1: fleet.v1.CreateAircraftResponse
}
var file_fleet_proto_depIdxs = []int32{
	0, // 0: fleet.v1.FleetService.CreateAircraft:input_type -> fleet.v1.CreateAircraftRequest
	1, // 1: fleet.v1.FleetService.CreateAircraft:output_type -> fleet.v1.CreateAircraftResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
