// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: world.proto

package worldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: add validation
// request to create country
type CreateCountryRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Iso                       string                 `protobuf:"bytes,1,opt,name=iso,proto3" json:"iso,omitempty"`
	LocalName                 string                 `protobuf:"bytes,2,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName                  string                 `protobuf:"bytes,3,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	FlythroughPermissionPrice float64                `protobuf:"fixed64,4,opt,name=flythrough_permission_price,json=flythroughPermissionPrice,proto3" json:"flythrough_permission_price,omitempty"`
	LandPermissionPrice       float64                `protobuf:"fixed64,5,opt,name=land_permission_price,json=landPermissionPrice,proto3" json:"land_permission_price,omitempty"`
	CorpTaxRate               float64                `protobuf:"fixed64,6,opt,name=corp_tax_rate,json=corpTaxRate,proto3" json:"corp_tax_rate,omitempty"`
	VatRate                   float64                `protobuf:"fixed64,7,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`
	AircraftTailCode          string                 `protobuf:"bytes,8,opt,name=aircraft_tail_code,json=aircraftTailCode,proto3" json:"aircraft_tail_code,omitempty"`
	WikipediaLink             string                 `protobuf:"bytes,9,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	mi := &file_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCountryRequest) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

func (x *CreateCountryRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateCountryRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateCountryRequest) GetFlythroughPermissionPrice() float64 {
	if x != nil {
		return x.FlythroughPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetLandPermissionPrice() float64 {
	if x != nil {
		return x.LandPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetCorpTaxRate() float64 {
	if x != nil {
		return x.CorpTaxRate
	}
	return 0
}

func (x *CreateCountryRequest) GetVatRate() float64 {
	if x != nil {
		return x.VatRate
	}
	return 0
}

func (x *CreateCountryRequest) GetAircraftTailCode() string {
	if x != nil {
		return x.AircraftTailCode
	}
	return ""
}

func (x *CreateCountryRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type CreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalCode     string                 `protobuf:"bytes,2,opt,name=local_code,json=localCode,proto3" json:"local_code,omitempty"`
	LocalName     string                 `protobuf:"bytes,3,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName      string                 `protobuf:"bytes,4,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	CountryId     string                 `protobuf:"bytes,5,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Population    float64                `protobuf:"fixed64,6,opt,name=population,proto3" json:"population,omitempty"`
	GdpPerCapita  float64                `protobuf:"fixed64,7,opt,name=gdp_per_capita,json=gdpPerCapita,proto3" json:"gdp_per_capita,omitempty"`
	TourismScore  float64                `protobuf:"fixed64,8,opt,name=tourism_score,json=tourismScore,proto3" json:"tourism_score,omitempty"`
	BusinessScore float64                `protobuf:"fixed64,9,opt,name=business_score,json=businessScore,proto3" json:"business_score,omitempty"`
	WikipediaLink string                 `protobuf:"bytes,10,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRegionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRegionRequest) GetLocalCode() string {
	if x != nil {
		return x.LocalCode
	}
	return ""
}

func (x *CreateRegionRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateRegionRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateRegionRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateRegionRequest) GetPopulation() float64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateRegionRequest) GetGdpPerCapita() float64 {
	if x != nil {
		return x.GdpPerCapita
	}
	return 0
}

func (x *CreateRegionRequest) GetTourismScore() float64 {
	if x != nil {
		return x.TourismScore
	}
	return 0
}

func (x *CreateRegionRequest) GetBusinessScore() float64 {
	if x != nil {
		return x.BusinessScore
	}
	return 0
}

func (x *CreateRegionRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type CreateRegionLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionA       string                 `protobuf:"bytes,2,opt,name=region_a,json=regionA,proto3" json:"region_a,omitempty"`
	RegionB       string                 `protobuf:"bytes,3,opt,name=region_b,json=regionB,proto3" json:"region_b,omitempty"`
	Diaspora      float64                `protobuf:"fixed64,4,opt,name=diaspora,proto3" json:"diaspora,omitempty"`
	Business      float64                `protobuf:"fixed64,5,opt,name=business,proto3" json:"business,omitempty"`
	Tourism       float64                `protobuf:"fixed64,6,opt,name=tourism,proto3" json:"tourism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionLinkRequest) Reset() {
	*x = CreateRegionLinkRequest{}
	mi := &file_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionLinkRequest) ProtoMessage() {}

func (x *CreateRegionLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionLinkRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRegionLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetRegionA() string {
	if x != nil {
		return x.RegionA
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetRegionB() string {
	if x != nil {
		return x.RegionB
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetDiaspora() float64 {
	if x != nil {
		return x.Diaspora
	}
	return 0
}

func (x *CreateRegionLinkRequest) GetBusiness() float64 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *CreateRegionLinkRequest) GetTourism() float64 {
	if x != nil {
		return x.Tourism
	}
	return 0
}

type CreateAirportRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IcaoCode              string                 `protobuf:"bytes,2,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode              string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	LocalName             string                 `protobuf:"bytes,4,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName              string                 `protobuf:"bytes,5,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	Timezone              string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CountryId             string                 `protobuf:"bytes,7,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	RegionId              string                 `protobuf:"bytes,8,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Municipality          string                 `protobuf:"bytes,9,opt,name=municipality,proto3" json:"municipality,omitempty"`
	Continent             string                 `protobuf:"bytes,10,opt,name=continent,proto3" json:"continent,omitempty"`
	ElevationFt           float64                `protobuf:"fixed64,11,opt,name=elevation_ft,json=elevationFt,proto3" json:"elevation_ft,omitempty"`
	MaxRunwayLengthM      float64                `protobuf:"fixed64,12,opt,name=max_runway_length_m,json=maxRunwayLengthM,proto3" json:"max_runway_length_m,omitempty"`
	WorksAtNight          bool                   `protobuf:"varint,13,opt,name=works_at_night,json=worksAtNight,proto3" json:"works_at_night,omitempty"`
	MaxRunwayUsesPerDay   float64                `protobuf:"fixed64,14,opt,name=max_runway_uses_per_day,json=maxRunwayUsesPerDay,proto3" json:"max_runway_uses_per_day,omitempty"`
	TurnaroundPointPrice  float64                `protobuf:"fixed64,15,opt,name=turnaround_point_price,json=turnaroundPointPrice,proto3" json:"turnaround_point_price,omitempty"`
	MaintenancePointPrice float64                `protobuf:"fixed64,16,opt,name=maintenance_point_price,json=maintenancePointPrice,proto3" json:"maintenance_point_price,omitempty"`
	RunwayFee             float64                `protobuf:"fixed64,17,opt,name=runway_fee,json=runwayFee,proto3" json:"runway_fee,omitempty"`
	GateFee               float64                `protobuf:"fixed64,18,opt,name=gate_fee,json=gateFee,proto3" json:"gate_fee,omitempty"`
	StandFee              float64                `protobuf:"fixed64,19,opt,name=stand_fee,json=standFee,proto3" json:"stand_fee,omitempty"`
	FuelPriceMultiplier   float64                `protobuf:"fixed64,20,opt,name=fuel_price_multiplier,json=fuelPriceMultiplier,proto3" json:"fuel_price_multiplier,omitempty"`
	HomeLink              string                 `protobuf:"bytes,21,opt,name=home_link,json=homeLink,proto3" json:"home_link,omitempty"`
	WikipediaLink         string                 `protobuf:"bytes,22,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	Geog                  string                 `protobuf:"bytes,23,opt,name=geog,proto3" json:"geog,omitempty"`
	Geom                  string                 `protobuf:"bytes,24,opt,name=geom,proto3" json:"geom,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateAirportRequest) Reset() {
	*x = CreateAirportRequest{}
	mi := &file_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAirportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportRequest) ProtoMessage() {}

func (x *CreateAirportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportRequest.ProtoReflect.Descriptor instead.
func (*CreateAirportRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAirportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAirportRequest) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *CreateAirportRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *CreateAirportRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateAirportRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateAirportRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateAirportRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateAirportRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *CreateAirportRequest) GetMunicipality() string {
	if x != nil {
		return x.Municipality
	}
	return ""
}

func (x *CreateAirportRequest) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *CreateAirportRequest) GetElevationFt() float64 {
	if x != nil {
		return x.ElevationFt
	}
	return 0
}

func (x *CreateAirportRequest) GetMaxRunwayLengthM() float64 {
	if x != nil {
		return x.MaxRunwayLengthM
	}
	return 0
}

func (x *CreateAirportRequest) GetWorksAtNight() bool {
	if x != nil {
		return x.WorksAtNight
	}
	return false
}

func (x *CreateAirportRequest) GetMaxRunwayUsesPerDay() float64 {
	if x != nil {
		return x.MaxRunwayUsesPerDay
	}
	return 0
}

func (x *CreateAirportRequest) GetTurnaroundPointPrice() float64 {
	if x != nil {
		return x.TurnaroundPointPrice
	}
	return 0
}

func (x *CreateAirportRequest) GetMaintenancePointPrice() float64 {
	if x != nil {
		return x.MaintenancePointPrice
	}
	return 0
}

func (x *CreateAirportRequest) GetRunwayFee() float64 {
	if x != nil {
		return x.RunwayFee
	}
	return 0
}

func (x *CreateAirportRequest) GetGateFee() float64 {
	if x != nil {
		return x.GateFee
	}
	return 0
}

func (x *CreateAirportRequest) GetStandFee() float64 {
	if x != nil {
		return x.StandFee
	}
	return 0
}

func (x *CreateAirportRequest) GetFuelPriceMultiplier() float64 {
	if x != nil {
		return x.FuelPriceMultiplier
	}
	return 0
}

func (x *CreateAirportRequest) GetHomeLink() string {
	if x != nil {
		return x.HomeLink
	}
	return ""
}

func (x *CreateAirportRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

func (x *CreateAirportRequest) GetGeog() string {
	if x != nil {
		return x.Geog
	}
	return ""
}

func (x *CreateAirportRequest) GetGeom() string {
	if x != nil {
		return x.Geom
	}
	return ""
}

type IDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDResponse) Reset() {
	*x = IDResponse{}
	mi := &file_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResponse) ProtoMessage() {}

func (x *IDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResponse.ProtoReflect.Descriptor instead.
func (*IDResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4}
}

func (x *IDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_world_proto protoreflect.FileDescriptor

const file_world_proto_rawDesc = "" +
	"\n" +
	"\vworld.proto\x12\aauth.v1\"\xec\x02\n" +
	"\x14CreateCountryRequest\x12\x10\n" +
	"\x03iso\x18\x01 \x01(\tR\x03iso\x12\x1d\n" +
	"\n" +
	"local_name\x18\x02 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x03 \x01(\tR\bintlName\x12>\n" +
	"\x1bflythrough_permission_price\x18\x04 \x01(\x01R\x19flythroughPermissionPrice\x122\n" +
	"\x15land_permission_price\x18\x05 \x01(\x01R\x13landPermissionPrice\x12\"\n" +
	"\rcorp_tax_rate\x18\x06 \x01(\x01R\vcorpTaxRate\x12\x19\n" +
	"\bvat_rate\x18\a \x01(\x01R\avatRate\x12,\n" +
	"\x12aircraft_tail_code\x18\b \x01(\tR\x10aircraftTailCode\x12%\n" +
	"\x0ewikipedia_link\x18\t \x01(\tR\rwikipediaLink\"\xd8\x02\n" +
	"\x13CreateRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_code\x18\x02 \x01(\tR\tlocalCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x03 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x04 \x01(\tR\bintlName\x12\x1d\n" +
	"\n" +
	"country_id\x18\x05 \x01(\tR\tcountryId\x12\x1e\n" +
	"\n" +
	"population\x18\x06 \x01(\x01R\n" +
	"population\x12$\n" +
	"\x0egdp_per_capita\x18\a \x01(\x01R\fgdpPerCapita\x12#\n" +
	"\rtourism_score\x18\b \x01(\x01R\ftourismScore\x12%\n" +
	"\x0ebusiness_score\x18\t \x01(\x01R\rbusinessScore\x12%\n" +
	"\x0ewikipedia_link\x18\n" +
	" \x01(\tR\rwikipediaLink\"\xb1\x01\n" +
	"\x17CreateRegionLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bregion_a\x18\x02 \x01(\tR\aregionA\x12\x19\n" +
	"\bregion_b\x18\x03 \x01(\tR\aregionB\x12\x1a\n" +
	"\bdiaspora\x18\x04 \x01(\x01R\bdiaspora\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\x01R\bbusiness\x12\x18\n" +
	"\atourism\x18\x06 \x01(\x01R\atourism\"\xc9\x06\n" +
	"\x14CreateAirportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ticao_code\x18\x02 \x01(\tR\bicaoCode\x12\x1b\n" +
	"\tiata_code\x18\x03 \x01(\tR\biataCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x04 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x05 \x01(\tR\bintlName\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"country_id\x18\a \x01(\tR\tcountryId\x12\x1b\n" +
	"\tregion_id\x18\b \x01(\tR\bregionId\x12\"\n" +
	"\fmunicipality\x18\t \x01(\tR\fmunicipality\x12\x1c\n" +
	"\tcontinent\x18\n" +
	" \x01(\tR\tcontinent\x12!\n" +
	"\felevation_ft\x18\v \x01(\x01R\velevationFt\x12-\n" +
	"\x13max_runway_length_m\x18\f \x01(\x01R\x10maxRunwayLengthM\x12$\n" +
	"\x0eworks_at_night\x18\r \x01(\bR\fworksAtNight\x124\n" +
	"\x17max_runway_uses_per_day\x18\x0e \x01(\x01R\x13maxRunwayUsesPerDay\x124\n" +
	"\x16turnaround_point_price\x18\x0f \x01(\x01R\x14turnaroundPointPrice\x126\n" +
	"\x17maintenance_point_price\x18\x10 \x01(\x01R\x15maintenancePointPrice\x12\x1d\n" +
	"\n" +
	"runway_fee\x18\x11 \x01(\x01R\trunwayFee\x12\x19\n" +
	"\bgate_fee\x18\x12 \x01(\x01R\agateFee\x12\x1b\n" +
	"\tstand_fee\x18\x13 \x01(\x01R\bstandFee\x122\n" +
	"\x15fuel_price_multiplier\x18\x14 \x01(\x01R\x13fuelPriceMultiplier\x12\x1b\n" +
	"\thome_link\x18\x15 \x01(\tR\bhomeLink\x12%\n" +
	"\x0ewikipedia_link\x18\x16 \x01(\tR\rwikipediaLink\x12\x12\n" +
	"\x04geog\x18\x17 \x01(\tR\x04geog\x12\x12\n" +
	"\x04geom\x18\x18 \x01(\tR\x04geom\"\x1c\n" +
	"\n" +
	"IDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xa6\x02\n" +
	"\fWorldService\x12C\n" +
	"\rCreateCountry\x12\x1d.auth.v1.CreateCountryRequest\x1a\x13.auth.v1.IDResponse\x12A\n" +
	"\fCreateRegion\x12\x1c.auth.v1.CreateRegionRequest\x1a\x13.auth.v1.IDResponse\x12I\n" +
	"\x10CreateRegionLink\x12 .auth.v1.CreateRegionLinkRequest\x1a\x13.auth.v1.IDResponse\x12C\n" +
	"\rCreateAirport\x12\x1d.auth.v1.CreateAirportRequest\x1a\x13.auth.v1.IDResponseBWZUgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/world/v1;worldpbb\x06proto3"

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData []byte
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)))
	})
	return file_world_proto_rawDescData
}

var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_world_proto_goTypes = []any{
	(*CreateCountryRequest)(nil),    // 0: auth.v1.CreateCountryRequest
	(*CreateRegionRequest)(nil),     // 1: auth.v1.CreateRegionRequest
	(*CreateRegionLinkRequest)(nil), // 2: auth.v1.CreateRegionLinkRequest
	(*CreateAirportRequest)(nil),    // 3: auth.v1.CreateAirportRequest
	(*IDResponse)(nil),              // 4: auth.v1.IDResponse
}
var file_world_proto_depIdxs = []int32{
	0, // 0: auth.v1.WorldService.CreateCountry:input_type -> auth.v1.CreateCountryRequest
	1, // 1: auth.v1.WorldService.CreateRegion:input_type -> auth.v1.CreateRegionRequest
	2, // 2: auth.v1.WorldService.CreateRegionLink:input_type -> auth.v1.CreateRegionLinkRequest
	3, // 3: auth.v1.WorldService.CreateAirport:input_type -> auth.v1.CreateAirportRequest
	4, // 4: auth.v1.WorldService.CreateCountry:output_type -> auth.v1.IDResponse
	4, // 5: auth.v1.WorldService.CreateRegion:output_type -> auth.v1.IDResponse
	4, // 6: auth.v1.WorldService.CreateRegionLink:output_type -> auth.v1.IDResponse
	4, // 7: auth.v1.WorldService.CreateAirport:output_type -> auth.v1.IDResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
