// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: world.proto

package worldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request to create country
type CreateCountryRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Iso                       string                 `protobuf:"bytes,1,opt,name=iso,proto3" json:"iso,omitempty"`
	LocalName                 string                 `protobuf:"bytes,2,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName                  string                 `protobuf:"bytes,3,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	FlythroughPermissionPrice float64                `protobuf:"fixed64,4,opt,name=flythrough_permission_price,json=flythroughPermissionPrice,proto3" json:"flythrough_permission_price,omitempty"`
	LandPermissionPrice       float64                `protobuf:"fixed64,5,opt,name=land_permission_price,json=landPermissionPrice,proto3" json:"land_permission_price,omitempty"`
	CorpTaxRate               float64                `protobuf:"fixed64,6,opt,name=corp_tax_rate,json=corpTaxRate,proto3" json:"corp_tax_rate,omitempty"`
	VatRate                   float64                `protobuf:"fixed64,7,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`
	AircraftTailCode          string                 `protobuf:"bytes,8,opt,name=aircraft_tail_code,json=aircraftTailCode,proto3" json:"aircraft_tail_code,omitempty"`
	WikipediaLink             string                 `protobuf:"bytes,9,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	mi := &file_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCountryRequest) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

func (x *CreateCountryRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateCountryRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateCountryRequest) GetFlythroughPermissionPrice() float64 {
	if x != nil {
		return x.FlythroughPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetLandPermissionPrice() float64 {
	if x != nil {
		return x.LandPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetCorpTaxRate() float64 {
	if x != nil {
		return x.CorpTaxRate
	}
	return 0
}

func (x *CreateCountryRequest) GetVatRate() float64 {
	if x != nil {
		return x.VatRate
	}
	return 0
}

func (x *CreateCountryRequest) GetAircraftTailCode() string {
	if x != nil {
		return x.AircraftTailCode
	}
	return ""
}

func (x *CreateCountryRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type IDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDResponse) Reset() {
	*x = IDResponse{}
	mi := &file_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResponse) ProtoMessage() {}

func (x *IDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResponse.ProtoReflect.Descriptor instead.
func (*IDResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

func (x *IDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_world_proto protoreflect.FileDescriptor

const file_world_proto_rawDesc = "" +
	"\n" +
	"\vworld.proto\x12\aauth.v1\"\xec\x02\n" +
	"\x14CreateCountryRequest\x12\x10\n" +
	"\x03iso\x18\x01 \x01(\tR\x03iso\x12\x1d\n" +
	"\n" +
	"local_name\x18\x02 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x03 \x01(\tR\bintlName\x12>\n" +
	"\x1bflythrough_permission_price\x18\x04 \x01(\x01R\x19flythroughPermissionPrice\x122\n" +
	"\x15land_permission_price\x18\x05 \x01(\x01R\x13landPermissionPrice\x12\"\n" +
	"\rcorp_tax_rate\x18\x06 \x01(\x01R\vcorpTaxRate\x12\x19\n" +
	"\bvat_rate\x18\a \x01(\x01R\avatRate\x12,\n" +
	"\x12aircraft_tail_code\x18\b \x01(\tR\x10aircraftTailCode\x12%\n" +
	"\x0ewikipedia_link\x18\t \x01(\tR\rwikipediaLink\"\x1c\n" +
	"\n" +
	"IDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2S\n" +
	"\fWorldService\x12C\n" +
	"\rCreateCountry\x12\x1d.auth.v1.CreateCountryRequest\x1a\x13.auth.v1.IDResponseBWZUgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/world/v1;worldpbb\x06proto3"

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData []byte
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)))
	})
	return file_world_proto_rawDescData
}

var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_world_proto_goTypes = []any{
	(*CreateCountryRequest)(nil), // 0: auth.v1.CreateCountryRequest
	(*IDResponse)(nil),           // 1: auth.v1.IDResponse
}
var file_world_proto_depIdxs = []int32{
	0, // 0: auth.v1.WorldService.CreateCountry:input_type -> auth.v1.CreateCountryRequest
	1, // 1: auth.v1.WorldService.CreateCountry:output_type -> auth.v1.IDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
