// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: world.proto

package worldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: add validation
// request to create country
type CreateCountryRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Iso                       string                 `protobuf:"bytes,1,opt,name=iso,proto3" json:"iso,omitempty"`
	LocalName                 string                 `protobuf:"bytes,2,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName                  string                 `protobuf:"bytes,3,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	FlythroughPermissionPrice float64                `protobuf:"fixed64,4,opt,name=flythrough_permission_price,json=flythroughPermissionPrice,proto3" json:"flythrough_permission_price,omitempty"`
	LandPermissionPrice       float64                `protobuf:"fixed64,5,opt,name=land_permission_price,json=landPermissionPrice,proto3" json:"land_permission_price,omitempty"`
	CorpTaxRate               float64                `protobuf:"fixed64,6,opt,name=corp_tax_rate,json=corpTaxRate,proto3" json:"corp_tax_rate,omitempty"`
	VatRate                   float64                `protobuf:"fixed64,7,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`
	AircraftTailCode          string                 `protobuf:"bytes,8,opt,name=aircraft_tail_code,json=aircraftTailCode,proto3" json:"aircraft_tail_code,omitempty"`
	WikipediaLink             string                 `protobuf:"bytes,9,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	mi := &file_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCountryRequest) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

func (x *CreateCountryRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateCountryRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateCountryRequest) GetFlythroughPermissionPrice() float64 {
	if x != nil {
		return x.FlythroughPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetLandPermissionPrice() float64 {
	if x != nil {
		return x.LandPermissionPrice
	}
	return 0
}

func (x *CreateCountryRequest) GetCorpTaxRate() float64 {
	if x != nil {
		return x.CorpTaxRate
	}
	return 0
}

func (x *CreateCountryRequest) GetVatRate() float64 {
	if x != nil {
		return x.VatRate
	}
	return 0
}

func (x *CreateCountryRequest) GetAircraftTailCode() string {
	if x != nil {
		return x.AircraftTailCode
	}
	return ""
}

func (x *CreateCountryRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type ListCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesRequest) Reset() {
	*x = ListCountriesRequest{}
	mi := &file_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesRequest) ProtoMessage() {}

func (x *ListCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesRequest.ProtoReflect.Descriptor instead.
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

type Country struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Iso                       string                 `protobuf:"bytes,2,opt,name=iso,proto3" json:"iso,omitempty"`
	LocalName                 string                 `protobuf:"bytes,3,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName                  string                 `protobuf:"bytes,4,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	FlythroughPermissionPrice float64                `protobuf:"fixed64,5,opt,name=flythrough_permission_price,json=flythroughPermissionPrice,proto3" json:"flythrough_permission_price,omitempty"`
	LandPermissionPrice       float64                `protobuf:"fixed64,6,opt,name=land_permission_price,json=landPermissionPrice,proto3" json:"land_permission_price,omitempty"`
	CorpTaxRate               float64                `protobuf:"fixed64,7,opt,name=corp_tax_rate,json=corpTaxRate,proto3" json:"corp_tax_rate,omitempty"`
	VatRate                   float64                `protobuf:"fixed64,8,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`
	AircraftTailCode          string                 `protobuf:"bytes,9,opt,name=aircraft_tail_code,json=aircraftTailCode,proto3" json:"aircraft_tail_code,omitempty"`
	WikipediaLink             string                 `protobuf:"bytes,10,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

func (x *Country) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Country) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

func (x *Country) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *Country) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *Country) GetFlythroughPermissionPrice() float64 {
	if x != nil {
		return x.FlythroughPermissionPrice
	}
	return 0
}

func (x *Country) GetLandPermissionPrice() float64 {
	if x != nil {
		return x.LandPermissionPrice
	}
	return 0
}

func (x *Country) GetCorpTaxRate() float64 {
	if x != nil {
		return x.CorpTaxRate
	}
	return 0
}

func (x *Country) GetVatRate() float64 {
	if x != nil {
		return x.VatRate
	}
	return 0
}

func (x *Country) GetAircraftTailCode() string {
	if x != nil {
		return x.AircraftTailCode
	}
	return ""
}

func (x *Country) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type ListCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesResponse) Reset() {
	*x = ListCountriesResponse{}
	mi := &file_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesResponse) ProtoMessage() {}

func (x *ListCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesResponse.ProtoReflect.Descriptor instead.
func (*ListCountriesResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3}
}

func (x *ListCountriesResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type DeleteCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCountryRequest) Reset() {
	*x = DeleteCountryRequest{}
	mi := &file_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryRequest) ProtoMessage() {}

func (x *DeleteCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCountryRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCountryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// request to create region
type CreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalCode     string                 `protobuf:"bytes,2,opt,name=local_code,json=localCode,proto3" json:"local_code,omitempty"`
	LocalName     string                 `protobuf:"bytes,3,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName      string                 `protobuf:"bytes,4,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	CountryId     string                 `protobuf:"bytes,5,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Population    float64                `protobuf:"fixed64,6,opt,name=population,proto3" json:"population,omitempty"`
	GdpPerCapita  float64                `protobuf:"fixed64,7,opt,name=gdp_per_capita,json=gdpPerCapita,proto3" json:"gdp_per_capita,omitempty"`
	TourismScore  float64                `protobuf:"fixed64,8,opt,name=tourism_score,json=tourismScore,proto3" json:"tourism_score,omitempty"`
	BusinessScore float64                `protobuf:"fixed64,9,opt,name=business_score,json=businessScore,proto3" json:"business_score,omitempty"`
	WikipediaLink string                 `protobuf:"bytes,10,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRegionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRegionRequest) GetLocalCode() string {
	if x != nil {
		return x.LocalCode
	}
	return ""
}

func (x *CreateRegionRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateRegionRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateRegionRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateRegionRequest) GetPopulation() float64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateRegionRequest) GetGdpPerCapita() float64 {
	if x != nil {
		return x.GdpPerCapita
	}
	return 0
}

func (x *CreateRegionRequest) GetTourismScore() float64 {
	if x != nil {
		return x.TourismScore
	}
	return 0
}

func (x *CreateRegionRequest) GetBusinessScore() float64 {
	if x != nil {
		return x.BusinessScore
	}
	return 0
}

func (x *CreateRegionRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type ListRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsRequest) Reset() {
	*x = ListRegionsRequest{}
	mi := &file_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsRequest) ProtoMessage() {}

func (x *ListRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsRequest.ProtoReflect.Descriptor instead.
func (*ListRegionsRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{6}
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalCode     string                 `protobuf:"bytes,2,opt,name=local_code,json=localCode,proto3" json:"local_code,omitempty"`
	LocalName     string                 `protobuf:"bytes,3,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName      string                 `protobuf:"bytes,4,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	CountryId     string                 `protobuf:"bytes,5,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Population    float64                `protobuf:"fixed64,6,opt,name=population,proto3" json:"population,omitempty"`
	GdpPerCapita  float64                `protobuf:"fixed64,7,opt,name=gdp_per_capita,json=gdpPerCapita,proto3" json:"gdp_per_capita,omitempty"`
	TourismScore  float64                `protobuf:"fixed64,8,opt,name=tourism_score,json=tourismScore,proto3" json:"tourism_score,omitempty"`
	BusinessScore float64                `protobuf:"fixed64,9,opt,name=business_score,json=businessScore,proto3" json:"business_score,omitempty"`
	WikipediaLink string                 `protobuf:"bytes,10,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{7}
}

func (x *Region) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Region) GetLocalCode() string {
	if x != nil {
		return x.LocalCode
	}
	return ""
}

func (x *Region) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *Region) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *Region) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *Region) GetPopulation() float64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *Region) GetGdpPerCapita() float64 {
	if x != nil {
		return x.GdpPerCapita
	}
	return 0
}

func (x *Region) GetTourismScore() float64 {
	if x != nil {
		return x.TourismScore
	}
	return 0
}

func (x *Region) GetBusinessScore() float64 {
	if x != nil {
		return x.BusinessScore
	}
	return 0
}

func (x *Region) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

type ListRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsResponse) Reset() {
	*x = ListRegionsResponse{}
	mi := &file_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsResponse) ProtoMessage() {}

func (x *ListRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsResponse.ProtoReflect.Descriptor instead.
func (*ListRegionsResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{8}
}

func (x *ListRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

type DeleteRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRegionRequest) Reset() {
	*x = DeleteRegionRequest{}
	mi := &file_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegionRequest) ProtoMessage() {}

func (x *DeleteRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegionRequest.ProtoReflect.Descriptor instead.
func (*DeleteRegionRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRegionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// request to create region link
type CreateRegionLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionA       string                 `protobuf:"bytes,2,opt,name=region_a,json=regionA,proto3" json:"region_a,omitempty"`
	RegionB       string                 `protobuf:"bytes,3,opt,name=region_b,json=regionB,proto3" json:"region_b,omitempty"`
	Diaspora      float64                `protobuf:"fixed64,4,opt,name=diaspora,proto3" json:"diaspora,omitempty"`
	Business      float64                `protobuf:"fixed64,5,opt,name=business,proto3" json:"business,omitempty"`
	Tourism       float64                `protobuf:"fixed64,6,opt,name=tourism,proto3" json:"tourism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionLinkRequest) Reset() {
	*x = CreateRegionLinkRequest{}
	mi := &file_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionLinkRequest) ProtoMessage() {}

func (x *CreateRegionLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionLinkRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRegionLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetRegionA() string {
	if x != nil {
		return x.RegionA
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetRegionB() string {
	if x != nil {
		return x.RegionB
	}
	return ""
}

func (x *CreateRegionLinkRequest) GetDiaspora() float64 {
	if x != nil {
		return x.Diaspora
	}
	return 0
}

func (x *CreateRegionLinkRequest) GetBusiness() float64 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *CreateRegionLinkRequest) GetTourism() float64 {
	if x != nil {
		return x.Tourism
	}
	return 0
}

type ListRegionLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionLinksRequest) Reset() {
	*x = ListRegionLinksRequest{}
	mi := &file_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionLinksRequest) ProtoMessage() {}

func (x *ListRegionLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionLinksRequest.ProtoReflect.Descriptor instead.
func (*ListRegionLinksRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{11}
}

type RegionLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionA       string                 `protobuf:"bytes,2,opt,name=region_a,json=regionA,proto3" json:"region_a,omitempty"`
	RegionB       string                 `protobuf:"bytes,3,opt,name=region_b,json=regionB,proto3" json:"region_b,omitempty"`
	Diaspora      float64                `protobuf:"fixed64,4,opt,name=diaspora,proto3" json:"diaspora,omitempty"`
	Business      float64                `protobuf:"fixed64,5,opt,name=business,proto3" json:"business,omitempty"`
	Tourism       float64                `protobuf:"fixed64,6,opt,name=tourism,proto3" json:"tourism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionLink) Reset() {
	*x = RegionLink{}
	mi := &file_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionLink) ProtoMessage() {}

func (x *RegionLink) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionLink.ProtoReflect.Descriptor instead.
func (*RegionLink) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{12}
}

func (x *RegionLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegionLink) GetRegionA() string {
	if x != nil {
		return x.RegionA
	}
	return ""
}

func (x *RegionLink) GetRegionB() string {
	if x != nil {
		return x.RegionB
	}
	return ""
}

func (x *RegionLink) GetDiaspora() float64 {
	if x != nil {
		return x.Diaspora
	}
	return 0
}

func (x *RegionLink) GetBusiness() float64 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *RegionLink) GetTourism() float64 {
	if x != nil {
		return x.Tourism
	}
	return 0
}

type ListRegionLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionLinks   []*RegionLink          `protobuf:"bytes,1,rep,name=region_links,json=regionLinks,proto3" json:"region_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionLinksResponse) Reset() {
	*x = ListRegionLinksResponse{}
	mi := &file_world_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionLinksResponse) ProtoMessage() {}

func (x *ListRegionLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionLinksResponse.ProtoReflect.Descriptor instead.
func (*ListRegionLinksResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{13}
}

func (x *ListRegionLinksResponse) GetRegionLinks() []*RegionLink {
	if x != nil {
		return x.RegionLinks
	}
	return nil
}

type DeleteRegionLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRegionLinkRequest) Reset() {
	*x = DeleteRegionLinkRequest{}
	mi := &file_world_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRegionLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegionLinkRequest) ProtoMessage() {}

func (x *DeleteRegionLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegionLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteRegionLinkRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRegionLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// request to create airport
type CreateAirportRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IcaoCode              string                 `protobuf:"bytes,2,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode              string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	LocalName             string                 `protobuf:"bytes,4,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName              string                 `protobuf:"bytes,5,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	Timezone              string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CountryId             string                 `protobuf:"bytes,7,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	RegionId              string                 `protobuf:"bytes,8,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Municipality          string                 `protobuf:"bytes,9,opt,name=municipality,proto3" json:"municipality,omitempty"`
	Continent             string                 `protobuf:"bytes,10,opt,name=continent,proto3" json:"continent,omitempty"`
	ElevationFt           float64                `protobuf:"fixed64,11,opt,name=elevation_ft,json=elevationFt,proto3" json:"elevation_ft,omitempty"`
	MaxRunwayLengthM      float64                `protobuf:"fixed64,12,opt,name=max_runway_length_m,json=maxRunwayLengthM,proto3" json:"max_runway_length_m,omitempty"`
	WorksAtNight          bool                   `protobuf:"varint,13,opt,name=works_at_night,json=worksAtNight,proto3" json:"works_at_night,omitempty"`
	MaxRunwayUsesPerDay   float64                `protobuf:"fixed64,14,opt,name=max_runway_uses_per_day,json=maxRunwayUsesPerDay,proto3" json:"max_runway_uses_per_day,omitempty"`
	TurnaroundPointPrice  float64                `protobuf:"fixed64,15,opt,name=turnaround_point_price,json=turnaroundPointPrice,proto3" json:"turnaround_point_price,omitempty"`
	MaintenancePointPrice float64                `protobuf:"fixed64,16,opt,name=maintenance_point_price,json=maintenancePointPrice,proto3" json:"maintenance_point_price,omitempty"`
	RunwayFee             float64                `protobuf:"fixed64,17,opt,name=runway_fee,json=runwayFee,proto3" json:"runway_fee,omitempty"`
	GateFee               float64                `protobuf:"fixed64,18,opt,name=gate_fee,json=gateFee,proto3" json:"gate_fee,omitempty"`
	StandFee              float64                `protobuf:"fixed64,19,opt,name=stand_fee,json=standFee,proto3" json:"stand_fee,omitempty"`
	FuelPriceMultiplier   float64                `protobuf:"fixed64,20,opt,name=fuel_price_multiplier,json=fuelPriceMultiplier,proto3" json:"fuel_price_multiplier,omitempty"`
	HomeLink              string                 `protobuf:"bytes,21,opt,name=home_link,json=homeLink,proto3" json:"home_link,omitempty"`
	WikipediaLink         string                 `protobuf:"bytes,22,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	Geog                  string                 `protobuf:"bytes,23,opt,name=geog,proto3" json:"geog,omitempty"`
	Geom                  string                 `protobuf:"bytes,24,opt,name=geom,proto3" json:"geom,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateAirportRequest) Reset() {
	*x = CreateAirportRequest{}
	mi := &file_world_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAirportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportRequest) ProtoMessage() {}

func (x *CreateAirportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportRequest.ProtoReflect.Descriptor instead.
func (*CreateAirportRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{15}
}

func (x *CreateAirportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAirportRequest) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *CreateAirportRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *CreateAirportRequest) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *CreateAirportRequest) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *CreateAirportRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateAirportRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateAirportRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *CreateAirportRequest) GetMunicipality() string {
	if x != nil {
		return x.Municipality
	}
	return ""
}

func (x *CreateAirportRequest) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *CreateAirportRequest) GetElevationFt() float64 {
	if x != nil {
		return x.ElevationFt
	}
	return 0
}

func (x *CreateAirportRequest) GetMaxRunwayLengthM() float64 {
	if x != nil {
		return x.MaxRunwayLengthM
	}
	return 0
}

func (x *CreateAirportRequest) GetWorksAtNight() bool {
	if x != nil {
		return x.WorksAtNight
	}
	return false
}

func (x *CreateAirportRequest) GetMaxRunwayUsesPerDay() float64 {
	if x != nil {
		return x.MaxRunwayUsesPerDay
	}
	return 0
}

func (x *CreateAirportRequest) GetTurnaroundPointPrice() float64 {
	if x != nil {
		return x.TurnaroundPointPrice
	}
	return 0
}

func (x *CreateAirportRequest) GetMaintenancePointPrice() float64 {
	if x != nil {
		return x.MaintenancePointPrice
	}
	return 0
}

func (x *CreateAirportRequest) GetRunwayFee() float64 {
	if x != nil {
		return x.RunwayFee
	}
	return 0
}

func (x *CreateAirportRequest) GetGateFee() float64 {
	if x != nil {
		return x.GateFee
	}
	return 0
}

func (x *CreateAirportRequest) GetStandFee() float64 {
	if x != nil {
		return x.StandFee
	}
	return 0
}

func (x *CreateAirportRequest) GetFuelPriceMultiplier() float64 {
	if x != nil {
		return x.FuelPriceMultiplier
	}
	return 0
}

func (x *CreateAirportRequest) GetHomeLink() string {
	if x != nil {
		return x.HomeLink
	}
	return ""
}

func (x *CreateAirportRequest) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

func (x *CreateAirportRequest) GetGeog() string {
	if x != nil {
		return x.Geog
	}
	return ""
}

func (x *CreateAirportRequest) GetGeom() string {
	if x != nil {
		return x.Geom
	}
	return ""
}

type ListAirportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAirportsRequest) Reset() {
	*x = ListAirportsRequest{}
	mi := &file_world_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirportsRequest) ProtoMessage() {}

func (x *ListAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirportsRequest.ProtoReflect.Descriptor instead.
func (*ListAirportsRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{16}
}

type Airport struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IcaoCode              string                 `protobuf:"bytes,2,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode              string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	LocalName             string                 `protobuf:"bytes,4,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	IntlName              string                 `protobuf:"bytes,5,opt,name=intl_name,json=intlName,proto3" json:"intl_name,omitempty"`
	Timezone              string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CountryId             string                 `protobuf:"bytes,7,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	RegionId              string                 `protobuf:"bytes,8,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Municipality          string                 `protobuf:"bytes,9,opt,name=municipality,proto3" json:"municipality,omitempty"`
	Continent             string                 `protobuf:"bytes,10,opt,name=continent,proto3" json:"continent,omitempty"`
	ElevationFt           float64                `protobuf:"fixed64,11,opt,name=elevation_ft,json=elevationFt,proto3" json:"elevation_ft,omitempty"`
	MaxRunwayLengthM      float64                `protobuf:"fixed64,12,opt,name=max_runway_length_m,json=maxRunwayLengthM,proto3" json:"max_runway_length_m,omitempty"`
	WorksAtNight          bool                   `protobuf:"varint,13,opt,name=works_at_night,json=worksAtNight,proto3" json:"works_at_night,omitempty"`
	MaxRunwayUsesPerDay   float64                `protobuf:"fixed64,14,opt,name=max_runway_uses_per_day,json=maxRunwayUsesPerDay,proto3" json:"max_runway_uses_per_day,omitempty"`
	TurnaroundPointPrice  float64                `protobuf:"fixed64,15,opt,name=turnaround_point_price,json=turnaroundPointPrice,proto3" json:"turnaround_point_price,omitempty"`
	MaintenancePointPrice float64                `protobuf:"fixed64,16,opt,name=maintenance_point_price,json=maintenancePointPrice,proto3" json:"maintenance_point_price,omitempty"`
	RunwayFee             float64                `protobuf:"fixed64,17,opt,name=runway_fee,json=runwayFee,proto3" json:"runway_fee,omitempty"`
	GateFee               float64                `protobuf:"fixed64,18,opt,name=gate_fee,json=gateFee,proto3" json:"gate_fee,omitempty"`
	StandFee              float64                `protobuf:"fixed64,19,opt,name=stand_fee,json=standFee,proto3" json:"stand_fee,omitempty"`
	FuelPriceMultiplier   float64                `protobuf:"fixed64,20,opt,name=fuel_price_multiplier,json=fuelPriceMultiplier,proto3" json:"fuel_price_multiplier,omitempty"`
	HomeLink              string                 `protobuf:"bytes,21,opt,name=home_link,json=homeLink,proto3" json:"home_link,omitempty"`
	WikipediaLink         string                 `protobuf:"bytes,22,opt,name=wikipedia_link,json=wikipediaLink,proto3" json:"wikipedia_link,omitempty"`
	Geog                  string                 `protobuf:"bytes,23,opt,name=geog,proto3" json:"geog,omitempty"`
	Geom                  string                 `protobuf:"bytes,24,opt,name=geom,proto3" json:"geom,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Airport) Reset() {
	*x = Airport{}
	mi := &file_world_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Airport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airport) ProtoMessage() {}

func (x *Airport) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airport.ProtoReflect.Descriptor instead.
func (*Airport) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{17}
}

func (x *Airport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Airport) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *Airport) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *Airport) GetLocalName() string {
	if x != nil {
		return x.LocalName
	}
	return ""
}

func (x *Airport) GetIntlName() string {
	if x != nil {
		return x.IntlName
	}
	return ""
}

func (x *Airport) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Airport) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *Airport) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *Airport) GetMunicipality() string {
	if x != nil {
		return x.Municipality
	}
	return ""
}

func (x *Airport) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *Airport) GetElevationFt() float64 {
	if x != nil {
		return x.ElevationFt
	}
	return 0
}

func (x *Airport) GetMaxRunwayLengthM() float64 {
	if x != nil {
		return x.MaxRunwayLengthM
	}
	return 0
}

func (x *Airport) GetWorksAtNight() bool {
	if x != nil {
		return x.WorksAtNight
	}
	return false
}

func (x *Airport) GetMaxRunwayUsesPerDay() float64 {
	if x != nil {
		return x.MaxRunwayUsesPerDay
	}
	return 0
}

func (x *Airport) GetTurnaroundPointPrice() float64 {
	if x != nil {
		return x.TurnaroundPointPrice
	}
	return 0
}

func (x *Airport) GetMaintenancePointPrice() float64 {
	if x != nil {
		return x.MaintenancePointPrice
	}
	return 0
}

func (x *Airport) GetRunwayFee() float64 {
	if x != nil {
		return x.RunwayFee
	}
	return 0
}

func (x *Airport) GetGateFee() float64 {
	if x != nil {
		return x.GateFee
	}
	return 0
}

func (x *Airport) GetStandFee() float64 {
	if x != nil {
		return x.StandFee
	}
	return 0
}

func (x *Airport) GetFuelPriceMultiplier() float64 {
	if x != nil {
		return x.FuelPriceMultiplier
	}
	return 0
}

func (x *Airport) GetHomeLink() string {
	if x != nil {
		return x.HomeLink
	}
	return ""
}

func (x *Airport) GetWikipediaLink() string {
	if x != nil {
		return x.WikipediaLink
	}
	return ""
}

func (x *Airport) GetGeog() string {
	if x != nil {
		return x.Geog
	}
	return ""
}

func (x *Airport) GetGeom() string {
	if x != nil {
		return x.Geom
	}
	return ""
}

type ListAirportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Airports      []*Airport             `protobuf:"bytes,1,rep,name=airports,proto3" json:"airports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAirportsResponse) Reset() {
	*x = ListAirportsResponse{}
	mi := &file_world_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAirportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirportsResponse) ProtoMessage() {}

func (x *ListAirportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirportsResponse.ProtoReflect.Descriptor instead.
func (*ListAirportsResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{18}
}

func (x *ListAirportsResponse) GetAirports() []*Airport {
	if x != nil {
		return x.Airports
	}
	return nil
}

type DeleteAirportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAirportRequest) Reset() {
	*x = DeleteAirportRequest{}
	mi := &file_world_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAirportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAirportRequest) ProtoMessage() {}

func (x *DeleteAirportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAirportRequest.ProtoReflect.Descriptor instead.
func (*DeleteAirportRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAirportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// id of created instance response
type IDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDResponse) Reset() {
	*x = IDResponse{}
	mi := &file_world_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResponse) ProtoMessage() {}

func (x *IDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResponse.ProtoReflect.Descriptor instead.
func (*IDResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{20}
}

func (x *IDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_world_proto protoreflect.FileDescriptor

const file_world_proto_rawDesc = "" +
	"\n" +
	"\vworld.proto\x12\aauth.v1\"\xec\x02\n" +
	"\x14CreateCountryRequest\x12\x10\n" +
	"\x03iso\x18\x01 \x01(\tR\x03iso\x12\x1d\n" +
	"\n" +
	"local_name\x18\x02 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x03 \x01(\tR\bintlName\x12>\n" +
	"\x1bflythrough_permission_price\x18\x04 \x01(\x01R\x19flythroughPermissionPrice\x122\n" +
	"\x15land_permission_price\x18\x05 \x01(\x01R\x13landPermissionPrice\x12\"\n" +
	"\rcorp_tax_rate\x18\x06 \x01(\x01R\vcorpTaxRate\x12\x19\n" +
	"\bvat_rate\x18\a \x01(\x01R\avatRate\x12,\n" +
	"\x12aircraft_tail_code\x18\b \x01(\tR\x10aircraftTailCode\x12%\n" +
	"\x0ewikipedia_link\x18\t \x01(\tR\rwikipediaLink\"\x16\n" +
	"\x14ListCountriesRequest\"\xef\x02\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03iso\x18\x02 \x01(\tR\x03iso\x12\x1d\n" +
	"\n" +
	"local_name\x18\x03 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x04 \x01(\tR\bintlName\x12>\n" +
	"\x1bflythrough_permission_price\x18\x05 \x01(\x01R\x19flythroughPermissionPrice\x122\n" +
	"\x15land_permission_price\x18\x06 \x01(\x01R\x13landPermissionPrice\x12\"\n" +
	"\rcorp_tax_rate\x18\a \x01(\x01R\vcorpTaxRate\x12\x19\n" +
	"\bvat_rate\x18\b \x01(\x01R\avatRate\x12,\n" +
	"\x12aircraft_tail_code\x18\t \x01(\tR\x10aircraftTailCode\x12%\n" +
	"\x0ewikipedia_link\x18\n" +
	" \x01(\tR\rwikipediaLink\"G\n" +
	"\x15ListCountriesResponse\x12.\n" +
	"\tcountries\x18\x01 \x03(\v2\x10.auth.v1.CountryR\tcountries\"&\n" +
	"\x14DeleteCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\x02\n" +
	"\x13CreateRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_code\x18\x02 \x01(\tR\tlocalCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x03 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x04 \x01(\tR\bintlName\x12\x1d\n" +
	"\n" +
	"country_id\x18\x05 \x01(\tR\tcountryId\x12\x1e\n" +
	"\n" +
	"population\x18\x06 \x01(\x01R\n" +
	"population\x12$\n" +
	"\x0egdp_per_capita\x18\a \x01(\x01R\fgdpPerCapita\x12#\n" +
	"\rtourism_score\x18\b \x01(\x01R\ftourismScore\x12%\n" +
	"\x0ebusiness_score\x18\t \x01(\x01R\rbusinessScore\x12%\n" +
	"\x0ewikipedia_link\x18\n" +
	" \x01(\tR\rwikipediaLink\"\x14\n" +
	"\x12ListRegionsRequest\"\xcb\x02\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_code\x18\x02 \x01(\tR\tlocalCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x03 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x04 \x01(\tR\bintlName\x12\x1d\n" +
	"\n" +
	"country_id\x18\x05 \x01(\tR\tcountryId\x12\x1e\n" +
	"\n" +
	"population\x18\x06 \x01(\x01R\n" +
	"population\x12$\n" +
	"\x0egdp_per_capita\x18\a \x01(\x01R\fgdpPerCapita\x12#\n" +
	"\rtourism_score\x18\b \x01(\x01R\ftourismScore\x12%\n" +
	"\x0ebusiness_score\x18\t \x01(\x01R\rbusinessScore\x12%\n" +
	"\x0ewikipedia_link\x18\n" +
	" \x01(\tR\rwikipediaLink\"@\n" +
	"\x13ListRegionsResponse\x12)\n" +
	"\aregions\x18\x01 \x03(\v2\x0f.auth.v1.RegionR\aregions\"%\n" +
	"\x13DeleteRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb1\x01\n" +
	"\x17CreateRegionLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bregion_a\x18\x02 \x01(\tR\aregionA\x12\x19\n" +
	"\bregion_b\x18\x03 \x01(\tR\aregionB\x12\x1a\n" +
	"\bdiaspora\x18\x04 \x01(\x01R\bdiaspora\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\x01R\bbusiness\x12\x18\n" +
	"\atourism\x18\x06 \x01(\x01R\atourism\"\x18\n" +
	"\x16ListRegionLinksRequest\"\xa4\x01\n" +
	"\n" +
	"RegionLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bregion_a\x18\x02 \x01(\tR\aregionA\x12\x19\n" +
	"\bregion_b\x18\x03 \x01(\tR\aregionB\x12\x1a\n" +
	"\bdiaspora\x18\x04 \x01(\x01R\bdiaspora\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\x01R\bbusiness\x12\x18\n" +
	"\atourism\x18\x06 \x01(\x01R\atourism\"Q\n" +
	"\x17ListRegionLinksResponse\x126\n" +
	"\fregion_links\x18\x01 \x03(\v2\x13.auth.v1.RegionLinkR\vregionLinks\")\n" +
	"\x17DeleteRegionLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x06\n" +
	"\x14CreateAirportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ticao_code\x18\x02 \x01(\tR\bicaoCode\x12\x1b\n" +
	"\tiata_code\x18\x03 \x01(\tR\biataCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x04 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x05 \x01(\tR\bintlName\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"country_id\x18\a \x01(\tR\tcountryId\x12\x1b\n" +
	"\tregion_id\x18\b \x01(\tR\bregionId\x12\"\n" +
	"\fmunicipality\x18\t \x01(\tR\fmunicipality\x12\x1c\n" +
	"\tcontinent\x18\n" +
	" \x01(\tR\tcontinent\x12!\n" +
	"\felevation_ft\x18\v \x01(\x01R\velevationFt\x12-\n" +
	"\x13max_runway_length_m\x18\f \x01(\x01R\x10maxRunwayLengthM\x12$\n" +
	"\x0eworks_at_night\x18\r \x01(\bR\fworksAtNight\x124\n" +
	"\x17max_runway_uses_per_day\x18\x0e \x01(\x01R\x13maxRunwayUsesPerDay\x124\n" +
	"\x16turnaround_point_price\x18\x0f \x01(\x01R\x14turnaroundPointPrice\x126\n" +
	"\x17maintenance_point_price\x18\x10 \x01(\x01R\x15maintenancePointPrice\x12\x1d\n" +
	"\n" +
	"runway_fee\x18\x11 \x01(\x01R\trunwayFee\x12\x19\n" +
	"\bgate_fee\x18\x12 \x01(\x01R\agateFee\x12\x1b\n" +
	"\tstand_fee\x18\x13 \x01(\x01R\bstandFee\x122\n" +
	"\x15fuel_price_multiplier\x18\x14 \x01(\x01R\x13fuelPriceMultiplier\x12\x1b\n" +
	"\thome_link\x18\x15 \x01(\tR\bhomeLink\x12%\n" +
	"\x0ewikipedia_link\x18\x16 \x01(\tR\rwikipediaLink\x12\x12\n" +
	"\x04geog\x18\x17 \x01(\tR\x04geog\x12\x12\n" +
	"\x04geom\x18\x18 \x01(\tR\x04geom\"\x15\n" +
	"\x13ListAirportsRequest\"\xbc\x06\n" +
	"\aAirport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ticao_code\x18\x02 \x01(\tR\bicaoCode\x12\x1b\n" +
	"\tiata_code\x18\x03 \x01(\tR\biataCode\x12\x1d\n" +
	"\n" +
	"local_name\x18\x04 \x01(\tR\tlocalName\x12\x1b\n" +
	"\tintl_name\x18\x05 \x01(\tR\bintlName\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"country_id\x18\a \x01(\tR\tcountryId\x12\x1b\n" +
	"\tregion_id\x18\b \x01(\tR\bregionId\x12\"\n" +
	"\fmunicipality\x18\t \x01(\tR\fmunicipality\x12\x1c\n" +
	"\tcontinent\x18\n" +
	" \x01(\tR\tcontinent\x12!\n" +
	"\felevation_ft\x18\v \x01(\x01R\velevationFt\x12-\n" +
	"\x13max_runway_length_m\x18\f \x01(\x01R\x10maxRunwayLengthM\x12$\n" +
	"\x0eworks_at_night\x18\r \x01(\bR\fworksAtNight\x124\n" +
	"\x17max_runway_uses_per_day\x18\x0e \x01(\x01R\x13maxRunwayUsesPerDay\x124\n" +
	"\x16turnaround_point_price\x18\x0f \x01(\x01R\x14turnaroundPointPrice\x126\n" +
	"\x17maintenance_point_price\x18\x10 \x01(\x01R\x15maintenancePointPrice\x12\x1d\n" +
	"\n" +
	"runway_fee\x18\x11 \x01(\x01R\trunwayFee\x12\x19\n" +
	"\bgate_fee\x18\x12 \x01(\x01R\agateFee\x12\x1b\n" +
	"\tstand_fee\x18\x13 \x01(\x01R\bstandFee\x122\n" +
	"\x15fuel_price_multiplier\x18\x14 \x01(\x01R\x13fuelPriceMultiplier\x12\x1b\n" +
	"\thome_link\x18\x15 \x01(\tR\bhomeLink\x12%\n" +
	"\x0ewikipedia_link\x18\x16 \x01(\tR\rwikipediaLink\x12\x12\n" +
	"\x04geog\x18\x17 \x01(\tR\x04geog\x12\x12\n" +
	"\x04geom\x18\x18 \x01(\tR\x04geom\"D\n" +
	"\x14ListAirportsResponse\x12,\n" +
	"\bairports\x18\x01 \x03(\v2\x10.auth.v1.AirportR\bairports\"&\n" +
	"\x14DeleteAirportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"IDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xfb\x06\n" +
	"\fWorldService\x12C\n" +
	"\rCreateCountry\x12\x1d.auth.v1.CreateCountryRequest\x1a\x13.auth.v1.IDResponse\x12N\n" +
	"\rListCountries\x12\x1d.auth.v1.ListCountriesRequest\x1a\x1e.auth.v1.ListCountriesResponse\x12C\n" +
	"\rDeleteCountry\x12\x1d.auth.v1.DeleteCountryRequest\x1a\x13.auth.v1.IDResponse\x12A\n" +
	"\fCreateRegion\x12\x1c.auth.v1.CreateRegionRequest\x1a\x13.auth.v1.IDResponse\x12H\n" +
	"\vListRegions\x12\x1b.auth.v1.ListRegionsRequest\x1a\x1c.auth.v1.ListRegionsResponse\x12A\n" +
	"\fDeleteRegion\x12\x1c.auth.v1.DeleteRegionRequest\x1a\x13.auth.v1.IDResponse\x12I\n" +
	"\x10CreateRegionLink\x12 .auth.v1.CreateRegionLinkRequest\x1a\x13.auth.v1.IDResponse\x12T\n" +
	"\x0fListRegionLinks\x12\x1f.auth.v1.ListRegionLinksRequest\x1a .auth.v1.ListRegionLinksResponse\x12I\n" +
	"\x10DeleteRegionLink\x12 .auth.v1.DeleteRegionLinkRequest\x1a\x13.auth.v1.IDResponse\x12C\n" +
	"\rCreateAirport\x12\x1d.auth.v1.CreateAirportRequest\x1a\x13.auth.v1.IDResponse\x12K\n" +
	"\fListAirports\x12\x1c.auth.v1.ListAirportsRequest\x1a\x1d.auth.v1.ListAirportsResponse\x12C\n" +
	"\rDeleteAirport\x12\x1d.auth.v1.DeleteAirportRequest\x1a\x13.auth.v1.IDResponseBWZUgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/world/v1;worldpbb\x06proto3"

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData []byte
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)))
	})
	return file_world_proto_rawDescData
}

var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_world_proto_goTypes = []any{
	(*CreateCountryRequest)(nil),    // 0: auth.v1.CreateCountryRequest
	(*ListCountriesRequest)(nil),    // 1: auth.v1.ListCountriesRequest
	(*Country)(nil),                 // 2: auth.v1.Country
	(*ListCountriesResponse)(nil),   // 3: auth.v1.ListCountriesResponse
	(*DeleteCountryRequest)(nil),    // 4: auth.v1.DeleteCountryRequest
	(*CreateRegionRequest)(nil),     // 5: auth.v1.CreateRegionRequest
	(*ListRegionsRequest)(nil),      // 6: auth.v1.ListRegionsRequest
	(*Region)(nil),                  // 7: auth.v1.Region
	(*ListRegionsResponse)(nil),     // 8: auth.v1.ListRegionsResponse
	(*DeleteRegionRequest)(nil),     // 9: auth.v1.DeleteRegionRequest
	(*CreateRegionLinkRequest)(nil), // 10: auth.v1.CreateRegionLinkRequest
	(*ListRegionLinksRequest)(nil),  // 11: auth.v1.ListRegionLinksRequest
	(*RegionLink)(nil),              // 12: auth.v1.RegionLink
	(*ListRegionLinksResponse)(nil), // 13: auth.v1.ListRegionLinksResponse
	(*DeleteRegionLinkRequest)(nil), // 14: auth.v1.DeleteRegionLinkRequest
	(*CreateAirportRequest)(nil),    // 15: auth.v1.CreateAirportRequest
	(*ListAirportsRequest)(nil),     // 16: auth.v1.ListAirportsRequest
	(*Airport)(nil),                 // 17: auth.v1.Airport
	(*ListAirportsResponse)(nil),    // 18: auth.v1.ListAirportsResponse
	(*DeleteAirportRequest)(nil),    // 19: auth.v1.DeleteAirportRequest
	(*IDResponse)(nil),              // 20: auth.v1.IDResponse
}
var file_world_proto_depIdxs = []int32{
	2,  // 0: auth.v1.ListCountriesResponse.countries:type_name -> auth.v1.Country
	7,  // 1: auth.v1.ListRegionsResponse.regions:type_name -> auth.v1.Region
	12, // 2: auth.v1.ListRegionLinksResponse.region_links:type_name -> auth.v1.RegionLink
	17, // 3: auth.v1.ListAirportsResponse.airports:type_name -> auth.v1.Airport
	0,  // 4: auth.v1.WorldService.CreateCountry:input_type -> auth.v1.CreateCountryRequest
	1,  // 5: auth.v1.WorldService.ListCountries:input_type -> auth.v1.ListCountriesRequest
	4,  // 6: auth.v1.WorldService.DeleteCountry:input_type -> auth.v1.DeleteCountryRequest
	5,  // 7: auth.v1.WorldService.CreateRegion:input_type -> auth.v1.CreateRegionRequest
	6,  // 8: auth.v1.WorldService.ListRegions:input_type -> auth.v1.ListRegionsRequest
	9,  // 9: auth.v1.WorldService.DeleteRegion:input_type -> auth.v1.DeleteRegionRequest
	10, // 10: auth.v1.WorldService.CreateRegionLink:input_type -> auth.v1.CreateRegionLinkRequest
	11, // 11: auth.v1.WorldService.ListRegionLinks:input_type -> auth.v1.ListRegionLinksRequest
	14, // 12: auth.v1.WorldService.DeleteRegionLink:input_type -> auth.v1.DeleteRegionLinkRequest
	15, // 13: auth.v1.WorldService.CreateAirport:input_type -> auth.v1.CreateAirportRequest
	16, // 14: auth.v1.WorldService.ListAirports:input_type -> auth.v1.ListAirportsRequest
	19, // 15: auth.v1.WorldService.DeleteAirport:input_type -> auth.v1.DeleteAirportRequest
	20, // 16: auth.v1.WorldService.CreateCountry:output_type -> auth.v1.IDResponse
	3,  // 17: auth.v1.WorldService.ListCountries:output_type -> auth.v1.ListCountriesResponse
	20, // 18: auth.v1.WorldService.DeleteCountry:output_type -> auth.v1.IDResponse
	20, // 19: auth.v1.WorldService.CreateRegion:output_type -> auth.v1.IDResponse
	8,  // 20: auth.v1.WorldService.ListRegions:output_type -> auth.v1.ListRegionsResponse
	20, // 21: auth.v1.WorldService.DeleteRegion:output_type -> auth.v1.IDResponse
	20, // 22: auth.v1.WorldService.CreateRegionLink:output_type -> auth.v1.IDResponse
	13, // 23: auth.v1.WorldService.ListRegionLinks:output_type -> auth.v1.ListRegionLinksResponse
	20, // 24: auth.v1.WorldService.DeleteRegionLink:output_type -> auth.v1.IDResponse
	20, // 25: auth.v1.WorldService.CreateAirport:output_type -> auth.v1.IDResponse
	18, // 26: auth.v1.WorldService.ListAirports:output_type -> auth.v1.ListAirportsResponse
	20, // 27: auth.v1.WorldService.DeleteAirport:output_type -> auth.v1.IDResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
