// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: airline.proto

package airlinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request to create a new airline.
type CreateAirlineRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OwnerId           string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	StartingAirportId string                 `protobuf:"bytes,2,opt,name=starting_airport_id,json=startingAirportId,proto3" json:"starting_airport_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IataCode          string                 `protobuf:"bytes,4,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	IcaoCode          string                 `protobuf:"bytes,5,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAirlineRequest) Reset() {
	*x = CreateAirlineRequest{}
	mi := &file_airline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAirlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirlineRequest) ProtoMessage() {}

func (x *CreateAirlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_airline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirlineRequest.ProtoReflect.Descriptor instead.
func (*CreateAirlineRequest) Descriptor() ([]byte, []int) {
	return file_airline_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAirlineRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateAirlineRequest) GetStartingAirportId() string {
	if x != nil {
		return x.StartingAirportId
	}
	return ""
}

func (x *CreateAirlineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAirlineRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *CreateAirlineRequest) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

// response with id and balance of created entity
type CreateAirlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAirlineResponse) Reset() {
	*x = CreateAirlineResponse{}
	mi := &file_airline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAirlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirlineResponse) ProtoMessage() {}

func (x *CreateAirlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirlineResponse.ProtoReflect.Descriptor instead.
func (*CreateAirlineResponse) Descriptor() ([]byte, []int) {
	return file_airline_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAirlineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAirlineResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_airline_proto protoreflect.FileDescriptor

const file_airline_proto_rawDesc = "" +
	"\n" +
	"\rairline.proto\x12\aauth.v1\"\xaf\x01\n" +
	"\x14CreateAirlineRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12.\n" +
	"\x13starting_airport_id\x18\x02 \x01(\tR\x11startingAirportId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tiata_code\x18\x04 \x01(\tR\biataCode\x12\x1b\n" +
	"\ticao_code\x18\x05 \x01(\tR\bicaoCode\"A\n" +
	"\x15CreateAirlineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2`\n" +
	"\x0eAirlineService\x12N\n" +
	"\rCreateAirline\x12\x1d.auth.v1.CreateAirlineRequest\x1a\x1e.auth.v1.CreateAirlineResponseB[ZYgithub.com/404-u-team/airlinesim-mono/backend/shared/contracts/proto/airline/v1;airlinepbb\x06proto3"

var (
	file_airline_proto_rawDescOnce sync.Once
	file_airline_proto_rawDescData []byte
)

func file_airline_proto_rawDescGZIP() []byte {
	file_airline_proto_rawDescOnce.Do(func() {
		file_airline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_airline_proto_rawDesc), len(file_airline_proto_rawDesc)))
	})
	return file_airline_proto_rawDescData
}

var file_airline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_airline_proto_goTypes = []any{
	(*CreateAirlineRequest)(nil),  // 0: auth.v1.CreateAirlineRequest
	(*CreateAirlineResponse)(nil), // 1: auth.v1.CreateAirlineResponse
}
var file_airline_proto_depIdxs = []int32{
	0, // 0: auth.v1.AirlineService.CreateAirline:input_type -> auth.v1.CreateAirlineRequest
	1, // 1: auth.v1.AirlineService.CreateAirline:output_type -> auth.v1.CreateAirlineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_airline_proto_init() }
func file_airline_proto_init() {
	if File_airline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_airline_proto_rawDesc), len(file_airline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_airline_proto_goTypes,
		DependencyIndexes: file_airline_proto_depIdxs,
		MessageInfos:      file_airline_proto_msgTypes,
	}.Build()
	File_airline_proto = out.File
	file_airline_proto_goTypes = nil
	file_airline_proto_depIdxs = nil
}
