// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: airline.proto

package airlinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AirlineService_CreateAirline_FullMethodName       = "/auth.v1.AirlineService/CreateAirline"
	AirlineService_AdjustBalance_FullMethodName       = "/auth.v1.AirlineService/AdjustBalance"
	AirlineService_GetAirlineByID_FullMethodName      = "/auth.v1.AirlineService/GetAirlineByID"
	AirlineService_GetAirlineByOwnerID_FullMethodName = "/auth.v1.AirlineService/GetAirlineByOwnerID"
)

// AirlineServiceClient is the client API for AirlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// airline service
type AirlineServiceClient interface {
	// create country, returns id of newly created country
	CreateAirline(ctx context.Context, in *CreateAirlineRequest, opts ...grpc.CallOption) (*CreateAirlineResponse, error)
	// adjust airline balance by signed amount
	AdjustBalance(ctx context.Context, in *AdjustBalanceRequest, opts ...grpc.CallOption) (*AdjustBalanceResponse, error)
	// get airline by its id
	GetAirlineByID(ctx context.Context, in *GetAirlineByIDRequest, opts ...grpc.CallOption) (*AirlineResponse, error)
	// get authenticated user's airline
	GetAirlineByOwnerID(ctx context.Context, in *GetAirlineByOwnerIDRequest, opts ...grpc.CallOption) (*AirlineResponse, error)
}

type airlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirlineServiceClient(cc grpc.ClientConnInterface) AirlineServiceClient {
	return &airlineServiceClient{cc}
}

func (c *airlineServiceClient) CreateAirline(ctx context.Context, in *CreateAirlineRequest, opts ...grpc.CallOption) (*CreateAirlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAirlineResponse)
	err := c.cc.Invoke(ctx, AirlineService_CreateAirline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlineServiceClient) AdjustBalance(ctx context.Context, in *AdjustBalanceRequest, opts ...grpc.CallOption) (*AdjustBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustBalanceResponse)
	err := c.cc.Invoke(ctx, AirlineService_AdjustBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlineServiceClient) GetAirlineByID(ctx context.Context, in *GetAirlineByIDRequest, opts ...grpc.CallOption) (*AirlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AirlineResponse)
	err := c.cc.Invoke(ctx, AirlineService_GetAirlineByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlineServiceClient) GetAirlineByOwnerID(ctx context.Context, in *GetAirlineByOwnerIDRequest, opts ...grpc.CallOption) (*AirlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AirlineResponse)
	err := c.cc.Invoke(ctx, AirlineService_GetAirlineByOwnerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirlineServiceServer is the server API for AirlineService service.
// All implementations must embed UnimplementedAirlineServiceServer
// for forward compatibility.
//
// airline service
type AirlineServiceServer interface {
	// create country, returns id of newly created country
	CreateAirline(context.Context, *CreateAirlineRequest) (*CreateAirlineResponse, error)
	// adjust airline balance by signed amount
	AdjustBalance(context.Context, *AdjustBalanceRequest) (*AdjustBalanceResponse, error)
	// get airline by its id
	GetAirlineByID(context.Context, *GetAirlineByIDRequest) (*AirlineResponse, error)
	// get authenticated user's airline
	GetAirlineByOwnerID(context.Context, *GetAirlineByOwnerIDRequest) (*AirlineResponse, error)
	mustEmbedUnimplementedAirlineServiceServer()
}

// UnimplementedAirlineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAirlineServiceServer struct{}

func (UnimplementedAirlineServiceServer) CreateAirline(context.Context, *CreateAirlineRequest) (*CreateAirlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAirline not implemented")
}
func (UnimplementedAirlineServiceServer) AdjustBalance(context.Context, *AdjustBalanceRequest) (*AdjustBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustBalance not implemented")
}
func (UnimplementedAirlineServiceServer) GetAirlineByID(context.Context, *GetAirlineByIDRequest) (*AirlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAirlineByID not implemented")
}
func (UnimplementedAirlineServiceServer) GetAirlineByOwnerID(context.Context, *GetAirlineByOwnerIDRequest) (*AirlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAirlineByOwnerID not implemented")
}
func (UnimplementedAirlineServiceServer) mustEmbedUnimplementedAirlineServiceServer() {}
func (UnimplementedAirlineServiceServer) testEmbeddedByValue()                        {}

// UnsafeAirlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirlineServiceServer will
// result in compilation errors.
type UnsafeAirlineServiceServer interface {
	mustEmbedUnimplementedAirlineServiceServer()
}

func RegisterAirlineServiceServer(s grpc.ServiceRegistrar, srv AirlineServiceServer) {
	// If the following call panics, it indicates UnimplementedAirlineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AirlineService_ServiceDesc, srv)
}

func _AirlineService_CreateAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlineServiceServer).CreateAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirlineService_CreateAirline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlineServiceServer).CreateAirline(ctx, req.(*CreateAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlineService_AdjustBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlineServiceServer).AdjustBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirlineService_AdjustBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlineServiceServer).AdjustBalance(ctx, req.(*AdjustBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlineService_GetAirlineByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirlineByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlineServiceServer).GetAirlineByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirlineService_GetAirlineByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlineServiceServer).GetAirlineByID(ctx, req.(*GetAirlineByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlineService_GetAirlineByOwnerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirlineByOwnerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlineServiceServer).GetAirlineByOwnerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirlineService_GetAirlineByOwnerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlineServiceServer).GetAirlineByOwnerID(ctx, req.(*GetAirlineByOwnerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AirlineService_ServiceDesc is the grpc.ServiceDesc for AirlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AirlineService",
	HandlerType: (*AirlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAirline",
			Handler:    _AirlineService_CreateAirline_Handler,
		},
		{
			MethodName: "AdjustBalance",
			Handler:    _AirlineService_AdjustBalance_Handler,
		},
		{
			MethodName: "GetAirlineByID",
			Handler:    _AirlineService_GetAirlineByID_Handler,
		},
		{
			MethodName: "GetAirlineByOwnerID",
			Handler:    _AirlineService_GetAirlineByOwnerID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "airline.proto",
}
