definitions:
  dto.AccessTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  dto.CreateCountryRequest:
    properties:
      aircraft_tail_code:
        type: string
      corp_tax_rate:
        type: number
      flythrough_permission_price:
        type: number
      intl_name:
        type: string
      iso:
        type: string
      land_permission_price:
        type: number
      local_name:
        type: string
      vat_rate:
        type: number
      wikipedia_link:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: integer
    type: object
  dto.IDResponse:
    properties:
      id:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      login:
        maxLength: 50
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - login
    - password
    type: object
  dto.RegisterRequest:
    properties:
      email:
        maxLength: 255
        type: string
      nickname:
        maxLength: 50
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - email
    - nickname
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: lboris201@yandex.ru
    name: Jeno7u
    url: https://github.com/Jeno7u
  title: AirlineSim API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Returns access token and sets refresh token into cookie
      parameters:
      - description: User login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "400":
          description: 1 - request validation error, 2 - user not found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
      summary: Login user
      tags:
      - Auth
  /auth/refresh:
    post:
      description: Returns access token and sets refresh token into cookie
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "401":
          description: Refresh token or user is not valid
        "500":
          description: Internal server error
      summary: Refreshes access and refresh token using refresh token stored in cookies
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Returns access token and sets refresh token into cookie
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created and authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "400":
          description: 1 - request validation error, 2 - email exists, 3 - nickname
            exists
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
      summary: Register user
      tags:
      - Auth
  /country:
    post:
      consumes:
      - application/json
      description: Returns
      parameters:
      - description: Country details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCountryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Country created successfully, id returned
          schema:
            $ref: '#/definitions/dto.IDResponse'
        "400":
          description: 1 - request validation error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Country with such ISO already exists
        "500":
          description: Internal server error
      summary: Create country (admin only)
      tags:
      - Country
schemes:
- http
- https
swagger: "2.0"
