definitions:
  dto.AccessTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: integer
    type: object
  dto.IDResponse:
    properties:
      id:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      login:
        maxLength: 50
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - login
    - password
    type: object
  dto.RegisterRequest:
    properties:
      email:
        maxLength: 255
        type: string
      nickname:
        maxLength: 50
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - email
    - nickname
    - password
    type: object
  worldpb.Airport:
    properties:
      continent:
        type: string
      country_id:
        type: string
      elevation_ft:
        type: number
      fuel_price_multiplier:
        type: number
      gate_fee:
        type: number
      geog:
        type: string
      geom:
        type: string
      home_link:
        type: string
      iata_code:
        type: string
      icao_code:
        type: string
      id:
        type: string
      intl_name:
        type: string
      local_name:
        type: string
      maintenance_point_price:
        type: number
      max_runway_length_m:
        type: number
      max_runway_uses_per_day:
        type: number
      municipality:
        type: string
      region_id:
        type: string
      runway_fee:
        type: number
      stand_fee:
        type: number
      timezone:
        type: string
      turnaround_point_price:
        type: number
      wikipedia_link:
        type: string
      works_at_night:
        type: boolean
    type: object
  worldpb.Country:
    properties:
      aircraft_tail_code:
        type: string
      corp_tax_rate:
        type: number
      flythrough_permission_price:
        type: number
      id:
        type: string
      intl_name:
        type: string
      iso:
        type: string
      land_permission_price:
        type: number
      local_name:
        type: string
      vat_rate:
        type: number
      wikipedia_link:
        type: string
    type: object
  worldpb.CreateAirportRequest:
    properties:
      continent:
        type: string
      country_id:
        type: string
      elevation_ft:
        type: number
      fuel_price_multiplier:
        type: number
      gate_fee:
        type: number
      geog:
        type: string
      geom:
        type: string
      home_link:
        type: string
      iata_code:
        type: string
      icao_code:
        type: string
      id:
        type: string
      intl_name:
        type: string
      local_name:
        type: string
      maintenance_point_price:
        type: number
      max_runway_length_m:
        type: number
      max_runway_uses_per_day:
        type: number
      municipality:
        type: string
      region_id:
        type: string
      runway_fee:
        type: number
      stand_fee:
        type: number
      timezone:
        type: string
      turnaround_point_price:
        type: number
      wikipedia_link:
        type: string
      works_at_night:
        type: boolean
    type: object
  worldpb.CreateCountryRequest:
    properties:
      aircraft_tail_code:
        type: string
      corp_tax_rate:
        type: number
      flythrough_permission_price:
        type: number
      intl_name:
        type: string
      iso:
        type: string
      land_permission_price:
        type: number
      local_name:
        type: string
      vat_rate:
        type: number
      wikipedia_link:
        type: string
    type: object
  worldpb.CreateRegionLinkRequest:
    properties:
      business:
        type: number
      diaspora:
        type: number
      id:
        type: string
      region_a:
        type: string
      region_b:
        type: string
      tourism:
        type: number
    type: object
  worldpb.CreateRegionRequest:
    properties:
      business_score:
        type: number
      country_id:
        type: string
      gdp_per_capita:
        type: number
      id:
        type: string
      intl_name:
        type: string
      local_code:
        type: string
      local_name:
        type: string
      population:
        type: number
      tourism_score:
        type: number
      wikipedia_link:
        type: string
    type: object
  worldpb.IDResponse:
    properties:
      id:
        type: string
    type: object
  worldpb.ListAirportsResponse:
    properties:
      airports:
        items:
          $ref: '#/definitions/worldpb.Airport'
        type: array
    type: object
  worldpb.ListCountriesResponse:
    properties:
      countries:
        items:
          $ref: '#/definitions/worldpb.Country'
        type: array
    type: object
  worldpb.ListRegionLinksResponse:
    properties:
      region_links:
        items:
          $ref: '#/definitions/worldpb.RegionLink'
        type: array
    type: object
  worldpb.ListRegionsResponse:
    properties:
      regions:
        items:
          $ref: '#/definitions/worldpb.Region'
        type: array
    type: object
  worldpb.Region:
    properties:
      business_score:
        type: number
      country_id:
        type: string
      gdp_per_capita:
        type: number
      id:
        type: string
      intl_name:
        type: string
      local_code:
        type: string
      local_name:
        type: string
      population:
        type: number
      tourism_score:
        type: number
      wikipedia_link:
        type: string
    type: object
  worldpb.RegionLink:
    properties:
      business:
        type: number
      diaspora:
        type: number
      id:
        type: string
      region_a:
        type: string
      region_b:
        type: string
      tourism:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: lboris201@yandex.ru
    name: Jeno7u
    url: https://github.com/Jeno7u
  title: AirlineSim API
  version: "1.0"
paths:
  /airport:
    post:
      consumes:
      - application/json
      description: Returns
      parameters:
      - description: Airport details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/worldpb.CreateAirportRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Airport created successfully, id returned
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - request validation error, 2 - country with such country_id
            dont exists, 3 - region with such region_id dont exists
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Airport with such ICAO/IATA already exists
        "500":
          description: Internal server error
      summary: Create Airport (admin only)
      tags:
      - Airport
  /airport/{id}:
    delete:
      description: Returns deleted airport id
      parameters:
      - description: Airport ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Airport deleted
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - invalid id
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Airport not found
        "500":
          description: Internal server error
      summary: Delete airport (admin only)
      tags:
      - Airport
  /airports:
    get:
      description: Returns all airports
      produces:
      - application/json
      responses:
        "200":
          description: Airports list
          schema:
            $ref: '#/definitions/worldpb.ListAirportsResponse'
        "500":
          description: Internal server error
      summary: List airports
      tags:
      - Airport
  /auth/login:
    post:
      consumes:
      - application/json
      description: Returns access token and sets refresh token into cookie
      parameters:
      - description: User login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "400":
          description: 1 - request validation error, 2 - user not found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
      summary: Login user
      tags:
      - Auth
  /auth/refresh:
    post:
      description: Returns access token and sets refresh token into cookie
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "401":
          description: Refresh token or user is not valid
        "500":
          description: Internal server error
      summary: Refreshes access and refresh token using refresh token stored in cookies
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Returns access token and sets refresh token into cookie
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created and authenticated
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
        "400":
          description: 1 - request validation error, 2 - email exists, 3 - nickname
            exists
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
      summary: Register user
      tags:
      - Auth
  /countries:
    get:
      description: Returns all countries
      produces:
      - application/json
      responses:
        "200":
          description: Countries list
          schema:
            $ref: '#/definitions/worldpb.ListCountriesResponse'
        "500":
          description: Internal server error
      summary: List countries
      tags:
      - Country
  /country:
    post:
      consumes:
      - application/json
      description: Returns
      parameters:
      - description: Country details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/worldpb.CreateCountryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Country created successfully, id returned
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - request validation error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Country with such ISO already exists
        "500":
          description: Internal server error
      summary: Create country (admin only)
      tags:
      - Country
  /country/{id}:
    delete:
      description: Returns deleted country id
      parameters:
      - description: Country ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Country deleted
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - invalid id
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Country not found
        "409":
          description: Country has dependencies
        "500":
          description: Internal server error
      summary: Delete country (admin only)
      tags:
      - Country
  /region:
    post:
      consumes:
      - application/json
      description: Returns
      parameters:
      - description: Region details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/worldpb.CreateRegionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Region created successfully, id returned
          schema:
            $ref: '#/definitions/dto.IDResponse'
        "400":
          description: 1 - request validation error, 2 - country with such country_id
            dont exists
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Region with such local code already exists
        "500":
          description: Internal server error
      summary: Create Region (admin only)
      tags:
      - Region
  /region-link:
    post:
      consumes:
      - application/json
      description: Returns
      parameters:
      - description: Region Link details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/worldpb.CreateRegionLinkRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Region Link created successfully, id returned
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - request validation error, 2 - region with such region_id
            dont exists
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Region Link with such regions already exists
        "500":
          description: Internal server error
      summary: Create Region Link (admin only)
      tags:
      - Region Link
  /region-link/{id}:
    delete:
      description: Returns deleted region link id
      parameters:
      - description: Region Link ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Region link deleted
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - invalid id
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Region link not found
        "500":
          description: Internal server error
      summary: Delete region link (admin only)
      tags:
      - Region Link
  /region-links:
    get:
      description: Returns all region links
      produces:
      - application/json
      responses:
        "200":
          description: Region links list
          schema:
            $ref: '#/definitions/worldpb.ListRegionLinksResponse'
        "500":
          description: Internal server error
      summary: List region links
      tags:
      - Region Link
  /region/{id}:
    delete:
      description: Returns deleted region id
      parameters:
      - description: Region ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Region deleted
          schema:
            $ref: '#/definitions/worldpb.IDResponse'
        "400":
          description: 1 - invalid id
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Region not found
        "409":
          description: Region has dependencies
        "500":
          description: Internal server error
      summary: Delete region (admin only)
      tags:
      - Region
  /regions:
    get:
      description: Returns all regions
      produces:
      - application/json
      responses:
        "200":
          description: Regions list
          schema:
            $ref: '#/definitions/worldpb.ListRegionsResponse'
        "500":
          description: Internal server error
      summary: List regions
      tags:
      - Region
schemes:
- http
- https
swagger: "2.0"
